

FileName:MSRAInitializer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/MSRAInitializer.py", line 5, in <module>
    input=queries, size=10,
NameError: name 'queries' is not defined


FileName:AsyncExecutor.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/AsyncExecutor.py", line 4, in <module>
    data_feed = fluid.DataFeedDesc('data.proto')
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/data_feed_desc.py", line 72, in __init__
    with open(proto_file, 'r') as f:
IOError: [Errno 2] No such file or directory: 'data.proto'


FileName:pad2d.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/pad2d.py", line 5, in <module>
    result = fluid.layers.pad2d(input=data, padding=[1,2,3,4], mode='reflect')
TypeError: pad2d() got an unexpected keyword argument 'padding'


FileName:polynomial_decay.py:
---------------------------

  File "./api_codes/polynomial_decay.py", line 8
    decayed_learning_rate = (learning_rate - end_learning_rate) *
                                                                ^
SyntaxError: invalid syntax


FileName:elementwise_div.py:
---------------------------

  File "./api_codes/elementwise_div.py", line 4
    shape(X) = (2, 3, 4, 5), shape(Y) = (,)
                                         ^
SyntaxError: invalid syntax


FileName:L2DecayRegularizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/L2DecayRegularizer.py", line 8, in <module>
    optimizer.minimize(avg_cost)
NameError: name 'avg_cost' is not defined


FileName:DistributeTranspiler(1).py:
---------------------------

  File "./api_codes/DistributeTranspiler(1).py", line 29
    num_trainers=len(trainers.split(",)),
                                        ^
SyntaxError: EOL while scanning string literal


FileName:LarsMomentumOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/LarsMomentumOptimizer.py", line 5, in <module>
    optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:py_reader_1.py:
---------------------------

  File "./api_codes/py_reader_1.py", line 16
    test_reader = fluid.layers.py_reader(capacity=32,
              ^
SyntaxError: invalid syntax


FileName:name_scope.py:
---------------------------

  File "./api_codes/name_scope.py", line 5
    ...
    ^
SyntaxError: invalid syntax


FileName:square_error_cost.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/square_error_cost.py", line 4, in <module>
    y = layers.data(name='y', shape=[1], dtype='float32')
NameError: name 'layers' is not defined


FileName:NumpyArrayInitializer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/NumpyArrayInitializer.py", line 4, in <module>
    fc = fluid.layers.fc(input=x, size=10,
NameError: name 'x' is not defined


FileName:autoincreased_step_counter.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/autoincreased_step_counter.py", line 5, in <module>
    counter_name='@LR_DECAY_COUNTER@', begin=begin, step=1)
NameError: name 'begin' is not defined


FileName:auc(1).py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/auc(1).py", line 5, in <module>
    prediction = network(image, is_infer=True)
NameError: name 'network' is not defined


FileName:reduce_sum.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/reduce_sum.py", line 8, in <module>
    fluid.layers.reduce_sum(x)  # [3.5]
NameError: name 'x' is not defined


FileName:row_conv.py:
---------------------------

successful


FileName:cross_entropy.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/cross_entropy.py", line 4, in <module>
    predict = fluid.layers.fc(input=net, size=classdim, act='softmax')
NameError: name 'net' is not defined


FileName:fill_constant_batch_size_like.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/fill_constant_batch_size_like.py", line 5, in <module>
    input=like, shape=[1], value=0, dtype='int64')
NameError: name 'like' is not defined


FileName:sequence_conv_pool.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sequence_conv_pool.py", line 4, in <module>
    input_dim = len(word_dict)
NameError: name 'word_dict' is not defined


FileName:lstm_unit.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/lstm_unit.py", line 4, in <module>
    x_t = fluid.layers.fc(input=x_t_data, size=10)
NameError: name 'x_t_data' is not defined


FileName:rank_loss.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/rank_loss.py", line 7, in <module>
    out = fluid.layers.rank_loss(label, left, right)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 8089, in rank_loss
    outputs={'Out': out})
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1662, in append_op
    attrs=kwargs.get("attrs", None))
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1069, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: All inputs must be 2-D tensors with shape [batch_size x 1]. at [/home/teamcity/work/3f8ad9e2362c55ac/paddle/fluid/operators/rank_loss_op.cc:43]
PaddlePaddle Call Stacks: 
0          0x10e2f16ecp void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 636
1          0x10e2f141bp paddle::platform::EnforceNotMet::EnforceNotMet(std::exception_ptr, char const*, int) + 139
2          0x10e61faefp paddle::operators::RankLossOp::InferShape(paddle::framework::InferShapeContext*) const + 1583
3          0x10e4423f8p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 1464
4          0x10e3b5506p void pybind11::cpp_function::initialize<pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void&&, paddle::framework::OpDesc (*)(paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 198
5          0x10e2b9558p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
6          0x101093297p PyEval_EvalFrameEx + 22391
7          0x10108d8c4p PyEval_EvalCodeEx + 2164
8          0x10100f723p function_call + 355
9          0x100fe6c55p PyObject_Call + 101
10         0x100ff6032p instancemethod_call + 162
11         0x100fe6c55p PyObject_Call + 101
12         0x101049cdfp slot_tp_init + 175
13         0x101045ba9p type_call + 313
14         0x100fe6c55p PyObject_Call + 101
15         0x101093168p PyEval_EvalFrameEx + 22088
16         0x10108d8c4p PyEval_EvalCodeEx + 2164
17         0x10100f723p function_call + 355
18         0x100fe6c55p PyObject_Call + 101
19         0x1010941f0p PyEval_EvalFrameEx + 26320
20         0x10108d8c4p PyEval_EvalCodeEx + 2164
21         0x101097c0dp fast_function + 109
22         0x101092f89p PyEval_EvalFrameEx + 21609
23         0x10108d8c4p PyEval_EvalCodeEx + 2164
24         0x101097c0dp fast_function + 109
25         0x101092f89p PyEval_EvalFrameEx + 21609
26         0x10108d8c4p PyEval_EvalCodeEx + 2164
27         0x10108d042p PyEval_EvalCode + 34
28         0x1010baa7dp PyRun_FileExFlags + 157
29         0x1010ba5c0p PyRun_SimpleFileExFlags + 816
30         0x1010d1452p Py_Main + 3506
31      0x7fff6b242ed9p start + 1
32                 0x2p



FileName:DetectionMAP.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DetectionMAP.py", line 4, in <module>
    exe = fluid.Executor(place)
NameError: name 'place' is not defined


FileName:create_py_reader_by_data.py:
---------------------------

  File "./api_codes/create_py_reader_by_data.py", line 10
    img, label = fluid.layers.read_file(reader)
      ^
SyntaxError: invalid syntax


FileName:append_backward.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/append_backward.py", line 6, in <module>
    avg_loss = fluid.layers.mean(loss)
NameError: name 'loss' is not defined


FileName:matmul.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/matmul.py", line 6, in <module>
    fluid.layers.matmul(x, y)  # out: [B, ..., M, N]
NameError: name 'x' is not defined


FileName:elementwise_add.py:
---------------------------

  File "./api_codes/elementwise_add.py", line 4
    shape(X) = (2, 3, 4, 5), shape(Y) = (,)
                                         ^
SyntaxError: invalid syntax


FileName:fill_constant.py:
---------------------------

successful


FileName:gather.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/gather.py", line 4, in <module>
    output = fluid.layers.gather(x, index)
NameError: name 'x' is not defined


FileName:huber_loss.py:
---------------------------

  File "./api_codes/huber_loss.py", line 5
    loss = fluid.layers.huber_loss(input=predictions, label=label, 1.0)
SyntaxError: non-keyword arg after keyword arg


FileName:Executor. close.py:
---------------------------

  File "./api_codes/Executor. close.py", line 6
    ...
    ^
SyntaxError: invalid syntax


FileName:DynamicRNN. memory.py:
---------------------------

successful


FileName:generate_mask_labels_1.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/generate_mask_labels_1.py", line 19, in <module>
    rois=rois,
NameError: name 'rois' is not defined


FileName:save_persistables.py:
---------------------------

successful


FileName:cast.py:
---------------------------

successful


FileName:ParallelExecutor.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/ParallelExecutor.py", line 4, in <module>
    train_exe = fluid.ParallelExecutor(use_cuda=True, loss_name=loss.name)
NameError: name 'loss' is not defined


FileName:psroi_pool.py:
---------------------------

  File "./api_codes/psroi_pool.py", line 4
    pool_out = fluid.layers.psroi_pool(input=x, rois=rois, 490, 1.0, 7, 7)
SyntaxError: non-keyword arg after keyword arg


FileName:glu.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/glu.py", line 5, in <module>
    output = fluid.nets.glu(input=data, dim=1)  # shape of output: [3, 3, 9]
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/nets.py", line 334, in glu
    a, b = layers.split(input, num_or_sections=2, dim=dim)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 4770, in split
    'axis': dim
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1662, in append_op
    attrs=kwargs.get("attrs", None))
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1069, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected in_axis_dim % num == 0, but received in_axis_dim % num:1 != 0:0.
tensor split does not result in an equal division at [/home/teamcity/work/3f8ad9e2362c55ac/paddle/fluid/operators/split_op.cc:44]
PaddlePaddle Call Stacks: 
0          0x11233b794p void paddle::platform::EnforceNotMet::Init<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*, int) + 628
1          0x11233b4c0p paddle::platform::EnforceNotMet::EnforceNotMet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int) + 80
2          0x11257ac85p paddle::operators::SplitOp::InferShape(paddle::framework::InferShapeContext*) const + 2293
3          0x1124873f8p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 1464
4          0x1123fa506p void pybind11::cpp_function::initialize<pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void&&, paddle::framework::OpDesc (*)(paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 198
5          0x1122fe558p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
6          0x106228297p PyEval_EvalFrameEx + 22391
7          0x1062228c4p PyEval_EvalCodeEx + 2164
8          0x1061a4723p function_call + 355
9          0x10617bc55p PyObject_Call + 101
10         0x10618b032p instancemethod_call + 162
11         0x10617bc55p PyObject_Call + 101
12         0x1061decdfp slot_tp_init + 175
13         0x1061daba9p type_call + 313
14         0x10617bc55p PyObject_Call + 101
15         0x106228168p PyEval_EvalFrameEx + 22088
16         0x1062228c4p PyEval_EvalCodeEx + 2164
17         0x1061a4723p function_call + 355
18         0x10617bc55p PyObject_Call + 101
19         0x1062291f0p PyEval_EvalFrameEx + 26320
20         0x1062228c4p PyEval_EvalCodeEx + 2164
21         0x10622cc0dp fast_function + 109
22         0x106227f89p PyEval_EvalFrameEx + 21609
23         0x1062228c4p PyEval_EvalCodeEx + 2164
24         0x10622cc0dp fast_function + 109
25         0x106227f89p PyEval_EvalFrameEx + 21609
26         0x1062228c4p PyEval_EvalCodeEx + 2164
27         0x10622cc0dp fast_function + 109
28         0x106227f89p PyEval_EvalFrameEx + 21609
29         0x1062228c4p PyEval_EvalCodeEx + 2164
30         0x106222042p PyEval_EvalCode + 34
31         0x10624fa7dp PyRun_FileExFlags + 157
32         0x10624f5c0p PyRun_SimpleFileExFlags + 816
33         0x106266452p Py_Main + 3506
34      0x7fff6b242ed9p start + 1
35                 0x2p



FileName:chunk_eval.py:
---------------------------

  File "./api_codes/chunk_eval.py", line 4
    ====== ====== ======  =====  ==  ============   =====  ===== =====  ==  =========
     ^
SyntaxError: invalid syntax


FileName:pow.py:
---------------------------

successful


FileName:sequence_pad.py:
---------------------------

successful


FileName:argsort.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/argsort.py", line 4, in <module>
    input = fluid.layers.data(data=[2, 3])
TypeError: data() got an unexpected keyword argument 'data'


FileName:shuffle_channel.py:
---------------------------

successful


FileName:Executor. run_2(1).py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Executor. run_2(1).py", line 4, in <module>
    x = numpy.random.random(size=(10, 1)).astype('float32')
NameError: name 'numpy' is not defined


FileName:resize_bilinear.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/resize_bilinear.py", line 4, in <module>
    out = fluid.layers.resize_bilinear(input, out_shape=[12, 12])
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 7320, in resize_bilinear
    align_corners, align_mode)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 7177, in image_resize
    dtype = helper.input_dtype()
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 95, in input_dtype
    dtype = each.dtype
AttributeError: 'NoneType' object has no attribute 'dtype'


FileName:logical_and.py:
---------------------------

successful


FileName:inverse_time_decay_1.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/inverse_time_decay_1.py", line 4, in <module>
    if staircase == True:
NameError: name 'staircase' is not defined


FileName:sequence_enumerate.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sequence_enumerate.py", line 4, in <module>
    x = fluid.layers.data(shape[30, 1], dtype='int32', lod_level=1)
NameError: name 'shape' is not defined


FileName:gaussian_random.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/gaussian_random.py", line 4, in <module>
    out = layers.gaussian_random(shape=[20, 30])
NameError: name 'layers' is not defined


FileName:WeightedAverage.py:
---------------------------

successful
/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/average.py:64: Warning: The WeightedAverage is deprecated, please use fluid.metrics.Accuracy instead.
  (self.__class__.__name__), Warning)


FileName:load_vars.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/load_vars.py", line 13, in <module>
    fluid.io.load_vars(executor=exe, dirname=path, main_program=prog,
NameError: name 'path' is not defined




FileName:elementwise_pow.py:
---------------------------

  File "./api_codes/elementwise_pow.py", line 4
    shape(X) = (2, 3, 4, 5), shape(Y) = (,)
                                         ^
SyntaxError: invalid syntax


FileName:target_assign.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/target_assign.py", line 4, in <module>
    matched_indices, matched_dist = fluid.layers.bipartite_match(iou)
NameError: name 'iou' is not defined


FileName:dynamic_lstm.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/dynamic_lstm.py", line 5, in <module>
    forward_proj = fluid.layers.fc(input=input_seq, size=hidden_dim * 4,
NameError: name 'input_seq' is not defined


FileName:hard_sigmoid.py:
---------------------------

successful


FileName:flatten.py:
---------------------------

successful


FileName:uniform_random_batch_size_like.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/uniform_random_batch_size_like.py", line 4, in <module>
    input = layers.data(name="input", shape=[13, 11], dtype='float32')
NameError: name 'layers' is not defined


FileName:equal.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/equal.py", line 4, in <module>
    less = fluid.layers.equal(x=label, y=limit)
NameError: name 'label' is not defined


FileName:dice_loss.py:
---------------------------

  File "./api_codes/dice_loss.py", line 5
    loss = fluid.layers.dice_loss(input=predictions, label=label, 2)
SyntaxError: non-keyword arg after keyword arg


FileName:tree_conv.py:
---------------------------

  File "./api_codes/tree_conv.py", line 4
    nodes_vector = layers.data(name='vectors', shape=[None, 10, 5], dtype='float32)
                                                                                  ^
SyntaxError: EOL while scanning string literal


FileName:bipartite_match.py:
---------------------------

successful


FileName:Program. clone_1.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Program. clone_1.py", line 16, in <module>
    sgd.minimize(loss)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 487, in minimize
    no_grad_set=no_grad_set)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 392, in backward
    no_grad_set, callbacks)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/backward.py", line 518, in append_backward
    _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/backward.py", line 354, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected dy_dims.size() == rank, but received dy_dims.size():1 != rank:2.
Input(Y@Grad) and Input(X) should have the same rank. at [/home/teamcity/work/3f8ad9e2362c55ac/paddle/fluid/operators/cross_entropy_op.cc:98]
PaddlePaddle Call Stacks: 
0          0x10ec91794p void paddle::platform::EnforceNotMet::Init<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*, int) + 628
1          0x10ec914c0p paddle::platform::EnforceNotMet::EnforceNotMet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int) + 80
2          0x10f39df23p paddle::operators::CrossEntropyGradientOpBase::InferShape(paddle::framework::InferShapeContext*) const + 2963
3          0x10f3a34c3p paddle::operators::CrossEntropyGradientOp2::InferShape(paddle::framework::InferShapeContext*) const + 99
4          0x10eddd3f8p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 1464
5          0x10ed50506p void pybind11::cpp_function::initialize<pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void&&, paddle::framework::OpDesc (*)(paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 198
6          0x10ec54558p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
7          0x102b7c297p PyEval_EvalFrameEx + 22391
8          0x102b768c4p PyEval_EvalCodeEx + 2164
9          0x102b80c0dp fast_function + 109
10         0x102b7bf89p PyEval_EvalFrameEx + 21609
11         0x102b768c4p PyEval_EvalCodeEx + 2164
12         0x102b80c0dp fast_function + 109
13         0x102b7bf89p PyEval_EvalFrameEx + 21609
14         0x102b768c4p PyEval_EvalCodeEx + 2164
15         0x102b80c0dp fast_function + 109
16         0x102b7bf89p PyEval_EvalFrameEx + 21609
17         0x102b768c4p PyEval_EvalCodeEx + 2164
18         0x102b80c0dp fast_function + 109
19         0x102b7bf89p PyEval_EvalFrameEx + 21609
20         0x102b768c4p PyEval_EvalCodeEx + 2164
21         0x102b76042p PyEval_EvalCode + 34
22         0x102ba3a7dp PyRun_FileExFlags + 157
23         0x102ba35c0p PyRun_SimpleFileExFlags + 816
24         0x102bba452p Py_Main + 3506
25      0x7fff6b242ed9p start + 1



FileName:elementwise_max.py:
---------------------------

  File "./api_codes/elementwise_max.py", line 4
    shape(X) = (2, 3, 4, 5), shape(Y) = (,)
                                         ^
SyntaxError: invalid syntax


FileName:zeros.py:
---------------------------

successful


FileName:gaussian_random_batch_size_like.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/gaussian_random_batch_size_like.py", line 4, in <module>
    input = layers.data(name="input", shape=[13, 11], dtype='float32')
NameError: name 'layers' is not defined


FileName:ssd_loss.py:
---------------------------

successful


FileName:pad_constant_like.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/pad_constant_like.py", line 6, in <module>
    out = fluid.layers.pad_constant_like(x=x, y=y, pad_value=0.)
NameError: name 'x' is not defined


FileName:sequence_scatter.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sequence_scatter.py", line 4, in <module>
    output = fluid.layers.sequence_scatter(input, index, updates)
NameError: name 'index' is not defined


FileName:ErrorClipByValue.py:
---------------------------

  File "./api_codes/ErrorClipByValue.py", line 4
    var = fluid.framework.Variable(..., error_clip=ErrorClipByValue(max=5.0), ...)
                                   ^
SyntaxError: invalid syntax


FileName:BuildStrategy.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/BuildStrategy.py", line 8, in <module>
    loss_name=loss.name,
NameError: name 'loss' is not defined


FileName:leaky_relu.py:
---------------------------

successful


FileName:im2sequence.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/im2sequence.py", line 5, in <module>
    input=layer, stride=[1, 1], filter_size=[2, 2])
NameError: name 'layer' is not defined


FileName:space_to_depth.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/space_to_depth.py", line 7, in <module>
    x=data, blocksize=2)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 9753, in space_to_depth
    outputs={"Out": out})
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1662, in append_op
    attrs=kwargs.get("attrs", None))
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1069, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected x_dims.size() == 4, but received x_dims.size():5 != 4:4.
input should be a 4D tensor at [/home/teamcity/work/3f8ad9e2362c55ac/paddle/fluid/operators/space_to_depth_op.cc:33]
PaddlePaddle Call Stacks: 
0          0x113395794p void paddle::platform::EnforceNotMet::Init<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*, int) + 628
1          0x1133954c0p paddle::platform::EnforceNotMet::EnforceNotMet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int) + 80
2          0x1135ec2fbp paddle::operators::SpaceToDepthOp::InferShape(paddle::framework::InferShapeContext*) const + 1451
3          0x1134e13f8p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 1464
4          0x113454506p void pybind11::cpp_function::initialize<pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void&&, paddle::framework::OpDesc (*)(paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 198
5          0x113358558p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
6          0x107041297p PyEval_EvalFrameEx + 22391
7          0x10703b8c4p PyEval_EvalCodeEx + 2164
8          0x106fbd723p function_call + 355
9          0x106f94c55p PyObject_Call + 101
10         0x106fa4032p instancemethod_call + 162
11         0x106f94c55p PyObject_Call + 101
12         0x106ff7cdfp slot_tp_init + 175
13         0x106ff3ba9p type_call + 313
14         0x106f94c55p PyObject_Call + 101
15         0x107041168p PyEval_EvalFrameEx + 22088
16         0x10703b8c4p PyEval_EvalCodeEx + 2164
17         0x106fbd723p function_call + 355
18         0x106f94c55p PyObject_Call + 101
19         0x1070421f0p PyEval_EvalFrameEx + 26320
20         0x10703b8c4p PyEval_EvalCodeEx + 2164
21         0x107045c0dp fast_function + 109
22         0x107040f89p PyEval_EvalFrameEx + 21609
23         0x10703b8c4p PyEval_EvalCodeEx + 2164
24         0x107045c0dp fast_function + 109
25         0x107040f89p PyEval_EvalFrameEx + 21609
26         0x10703b8c4p PyEval_EvalCodeEx + 2164
27         0x10703b042p PyEval_EvalCode + 34
28         0x107068a7dp PyRun_FileExFlags + 157
29         0x1070685c0p PyRun_SimpleFileExFlags + 816
30         0x10707f452p Py_Main + 3506
31      0x7fff6b242ed9p start + 1



FileName:DataFeedDesc. desc.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DataFeedDesc. desc.py", line 4, in <module>
    data_feed = fluid.DataFeedDesc('data.proto')
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/data_feed_desc.py", line 72, in __init__
    with open(proto_file, 'r') as f:
IOError: [Errno 2] No such file or directory: 'data.proto'


FileName:slice.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/slice.py", line 8, in <module>
    input = layers.data(
NameError: name 'layers' is not defined


FileName:sequence_last_step.py:
---------------------------

successful


FileName:lod_reset.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/lod_reset.py", line 4, in <module>
    x = layers.data(name='x', shape=[10])
NameError: name 'layers' is not defined


FileName:program_guard_1.py:
---------------------------

  File "./api_codes/program_guard_1.py", line 5
    data = ...
           ^
SyntaxError: invalid syntax


FileName:create_global_var.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/create_global_var.py", line 4, in <module>
    var = fluid.create_global_var(shape=[2,3], value=1.0, dtype='float32',
AttributeError: 'module' object has no attribute 'create_global_var'


FileName:ModelAverage.py:
---------------------------

  File "./api_codes/ModelAverage.py", line 11
    exe.run(fluid.default_main_program()...)
                                         ^
SyntaxError: invalid syntax


FileName:cuda_profiler.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/cuda_profiler.py", line 9, in <module>
    place = fluid.CUDAPlace(0)
paddle.fluid.core.EnforceNotMet: Cannot use CUDAPlace in CPU only version at [/home/teamcity/work/3f8ad9e2362c55ac/paddle/fluid/pybind/pybind.cc:806]
PaddlePaddle Call Stacks: 
0          0x1113b4794p void paddle::platform::EnforceNotMet::Init<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*, int) + 628
1          0x1113b44c0p paddle::platform::EnforceNotMet::EnforceNotMet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int) + 80
2          0x1114155fap void pybind11::cpp_function::initialize<paddle::pybind::pybind11_init_core(pybind11::module&)::$_76, void, paddle::platform::CUDAPlace&, int, pybind11::name, pybind11::is_method, pybind11::sibling>(paddle::pybind::pybind11_init_core(pybind11::module&)::$_76&&, void (*)(paddle::platform::CUDAPlace&, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&) + 250
3          0x111377558p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
4          0x1051e5c55p PyObject_Call + 101
5          0x1051f5032p instancemethod_call + 162
6          0x1051e5c55p PyObject_Call + 101
7          0x105248cdfp slot_tp_init + 175
8          0x105244ba9p type_call + 313
9          0x1051e5c55p PyObject_Call + 101
10         0x105292168p PyEval_EvalFrameEx + 22088
11         0x10528c8c4p PyEval_EvalCodeEx + 2164
12         0x10528c042p PyEval_EvalCode + 34
13         0x1052b9a7dp PyRun_FileExFlags + 157
14         0x1052b95c0p PyRun_SimpleFileExFlags + 816
15         0x1052d0452p Py_Main + 3506
16      0x7fff6b242ed9p start + 1



FileName:roi_align.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/roi_align.py", line 4, in <module>
    align_out = fluid.layers.roi_align(input=x,
NameError: name 'x' is not defined


FileName:Recall.py:
---------------------------

  File "./api_codes/Recall.py", line 5
    for pass in range(PASSES):
           ^
SyntaxError: invalid syntax


FileName:DecayedAdagradOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DecayedAdagradOptimizer.py", line 5, in <module>
    optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:embedding.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/embedding.py", line 4, in <module>
    dict_size = len(dataset.ids)
NameError: name 'dataset' is not defined


FileName:fc.py:
---------------------------

successful


FileName:L1DecayRegularizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/L1DecayRegularizer.py", line 8, in <module>
    optimizer.minimize(avg_cost)
NameError: name 'avg_cost' is not defined


FileName:concat.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/concat.py", line 4, in <module>
    out = fluid.layers.concat(input=[Efirst, Esecond, Ethird, Efourth])
NameError: name 'Efirst' is not defined


FileName:log.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/log.py", line 4, in <module>
    output = fluid.layers.log(x)
NameError: name 'x' is not defined


FileName:create_tensor.py:
---------------------------

successful


FileName:reduce_min.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/reduce_min.py", line 8, in <module>
    fluid.layers.reduce_min(x)  # [0.1]
NameError: name 'x' is not defined


FileName:increment.py:
---------------------------

successful


FileName:sequence_first_step.py:
---------------------------

successful


FileName:reverse.py:
---------------------------

  File "./api_codes/reverse.py", line 4
    out = fluid.layers.reverse(x=in, axis=0)
                                  ^
SyntaxError: invalid syntax


FileName:box_clip.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/box_clip.py", line 8, in <module>
    input=boxes, im_info=im_info, inplace=True)
TypeError: box_clip() got an unexpected keyword argument 'inplace'


FileName:array_read.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/array_read.py", line 6, in <module>
    arr = layers.array_read(tmp, i=i)
NameError: name 'layers' is not defined


FileName:huber_loss_2.py:
---------------------------

  File "./api_codes/huber_loss_2.py", line 4
    huber\_loss = 0.5 * (label - input) * (label - input)
                                                        ^
SyntaxError: unexpected character after line continuation character


FileName:clip_by_norm.py:
---------------------------

successful


FileName:load_persistables.py:
---------------------------

successful


FileName:lrn.py:
---------------------------

successful


FileName:margin_rank_loss.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/margin_rank_loss.py", line 7, in <module>
    out = fluid.layers.margin_rank_loss(label, left, right)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 8142, in margin_rank_loss
    attrs={'margin': margin})
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1662, in append_op
    attrs=kwargs.get("attrs", None))
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1069, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: All inputs must be 2-D tensor with shape [batch_size x 1]. at [/home/teamcity/work/3f8ad9e2362c55ac/paddle/fluid/operators/margin_rank_loss_op.cc:37]
PaddlePaddle Call Stacks: 
0          0x10d6016ecp void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 636
1          0x10d60141bp paddle::platform::EnforceNotMet::EnforceNotMet(std::exception_ptr, char const*, int) + 139
2          0x10d9eb66ep paddle::operators::MarginRankLossOp::InferShape(paddle::framework::InferShapeContext*) const + 1902
3          0x10d7523f8p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 1464
4          0x10d6c5506p void pybind11::cpp_function::initialize<pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void&&, paddle::framework::OpDesc (*)(paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 198
5          0x10d5c9558p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
6          0x1016b1297p PyEval_EvalFrameEx + 22391
7          0x1016ab8c4p PyEval_EvalCodeEx + 2164
8          0x10162d723p function_call + 355
9          0x101604c55p PyObject_Call + 101
10         0x101614032p instancemethod_call + 162
11         0x101604c55p PyObject_Call + 101
12         0x101667cdfp slot_tp_init + 175
13         0x101663ba9p type_call + 313
14         0x101604c55p PyObject_Call + 101
15         0x1016b1168p PyEval_EvalFrameEx + 22088
16         0x1016ab8c4p PyEval_EvalCodeEx + 2164
17         0x10162d723p function_call + 355
18         0x101604c55p PyObject_Call + 101
19         0x1016b21f0p PyEval_EvalFrameEx + 26320
20         0x1016ab8c4p PyEval_EvalCodeEx + 2164
21         0x1016b5c0dp fast_function + 109
22         0x1016b0f89p PyEval_EvalFrameEx + 21609
23         0x1016ab8c4p PyEval_EvalCodeEx + 2164
24         0x1016b5c0dp fast_function + 109
25         0x1016b0f89p PyEval_EvalFrameEx + 21609
26         0x1016ab8c4p PyEval_EvalCodeEx + 2164
27         0x1016ab042p PyEval_EvalCode + 34
28         0x1016d8a7dp PyRun_FileExFlags + 157
29         0x1016d85c0p PyRun_SimpleFileExFlags + 816
30         0x1016ef452p Py_Main + 3506
31      0x7fff6b242ed9p start + 1



FileName:EditDistance.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/EditDistance.py", line 4, in <module>
    distances, seq_num = fluid.layers.edit_distance(input, label)
NameError: name 'label' is not defined


FileName:Executor. run.py:
---------------------------

  File "./api_codes/Executor. run.py", line 10
    >>> adam.minimize(loss)
    ^
IndentationError: unexpected indent


FileName:RMSPropOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/RMSPropOptimizer.py", line 5, in <module>
    _, params_grads = optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:tensor_array_to_tensor.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/tensor_array_to_tensor.py", line 4, in <module>
    output, output_index = fluid.layers.tensor_array_to_tensor(input=tensor_array)
NameError: name 'tensor_array' is not defined


FileName:chunk_eval_2.py:
---------------------------

  File "./api_codes/chunk_eval_2.py", line 4
    Scheme Begin Inside End   Single
               ^
SyntaxError: invalid syntax


FileName:accuracy(1).py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/accuracy(1).py", line 5, in <module>
    label = fluid.layers.data(name="data", shape=[-1,1], dtype="int32")
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 100, in data
    is_data=True)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py", line 353, in create_global_variable
    *args, persistable=persistable, **kwargs)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1526, in create_var
    var = Variable(block=self, *args, **kwargs)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 440, in __init__
    "matched.".format(self.name, old_shape, shape))
ValueError: Variable data has been created before. the previous shape is (-1L, 32L, 32L); the new shape is (-1, 1). They are not matched.


FileName:ParallelExecutor. run_1.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/ParallelExecutor. run_1.py", line 4, in <module>
    exe = ParallelExecutor()
NameError: name 'ParallelExecutor' is not defined


FileName:load_inference_model.py:
---------------------------

  File "./api_codes/load_inference_model.py", line 7
    [inference_program, feed_target_names, fetch_targets] =
                                                          ^
SyntaxError: invalid syntax


FileName:GradientClipByValue.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/GradientClipByValue.py", line 9, in <module>
    clip=fluid.clip.GradientClipByValue(-1.0, 1.0))
TypeError: __init__() got an unexpected keyword argument 'clip'


FileName:scope_guard(1).py:
---------------------------

  File "./api_codes/scope_guard(1).py", line 4
    ...
    ^
SyntaxError: invalid syntax


FileName:logical_not.py:
---------------------------

successful


FileName:data_norm.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/data_norm.py", line 4, in <module>
    data = fluid.layers.data(input=x, size=200, param_attr='fc1.w')
NameError: name 'x' is not defined


FileName:batch.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/batch.py", line 10, in <module>
    buffer_size=2)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 901, in open_files
    shape_concat.extend(shape)
TypeError: 'int' object is not iterable


FileName:reshape.py:
---------------------------

successful


FileName:AsyncExecutor. download_data.py:
---------------------------

  File "./api_codes/AsyncExecutor. download_data.py", line 6
    "./data", "afs://
                    ^
SyntaxError: EOL while scanning string literal


FileName:sequence_concat.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sequence_concat.py", line 4, in <module>
    out = fluid.layers.sequence_concat(input=[seq1, seq2, seq3])
NameError: name 'seq1' is not defined


FileName:Executor. close(1).py:
---------------------------

  File "./api_codes/Executor. close(1).py", line 6
    ...
    ^
SyntaxError: invalid syntax


FileName:py_func.py:
---------------------------

successful


FileName:SGDOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/SGDOptimizer.py", line 5, in <module>
    sgd_optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:ExecutionStrategy.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/ExecutionStrategy.py", line 8, in <module>
    loss_name=loss.name,
NameError: name 'loss' is not defined


FileName:beam_search_decode.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/beam_search_decode.py", line 6, in <module>
    finished_ids, finished_scores = layers.beam_search_decode(
NameError: name 'layers' is not defined


FileName:scope_guard.py:
---------------------------

  File "./api_codes/scope_guard.py", line 4
    ...
    ^
SyntaxError: invalid syntax


FileName:group_norm.py:
---------------------------

successful


FileName:box_coder.py:
---------------------------

successful


FileName:MomentumOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/MomentumOptimizer.py", line 5, in <module>
    optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:bpr_loss.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/bpr_loss.py", line 4, in <module>
    cost = fluid.layers.bpr_loss(input=predict, label=label)
NameError: name 'predict' is not defined


FileName:detection_output.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/detection_output.py", line 4, in <module>
    pb = layers.data(name='prior_box', shape=[10, 4],
NameError: name 'layers' is not defined


FileName:Executor. run_2.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Executor. run_2.py", line 4, in <module>
    x = numpy.random.random(size=(10, 1)).astype('float32')
NameError: name 'numpy' is not defined


FileName:argmax.py:
---------------------------

  File "./api_codes/argmax.py", line 4
    out = fluid.layers.argmax(x=in, axis=0)
                                 ^
SyntaxError: invalid syntax


FileName:DistributeTranspiler.py:
---------------------------

  File "./api_codes/DistributeTranspiler.py", line 29
    num_trainers=len(trainers.split(",)),
                                        ^
SyntaxError: EOL while scanning string literal


FileName:logical_xor.py:
---------------------------

successful


FileName:Executor. run_1(1).py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Executor. run_1(1).py", line 4, in <module>
    cpu = core.CPUPlace()
NameError: name 'core' is not defined


FileName:BilinearInitializer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/BilinearInitializer.py", line 5, in <module>
    w_attr = ParamAttr(learning_rate=0., regularizer=L2Decay(0.),
NameError: name 'ParamAttr' is not defined


FileName:sequence_expand_as.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sequence_expand_as.py", line 7, in <module>
    out = layers.sequence_expand_as(x=x, y=y)
NameError: name 'layers' is not defined


FileName:DataFeeder_1.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DataFeeder_1.py", line 4, in <module>
    place=fluid.CUDAPlace(0)
paddle.fluid.core.EnforceNotMet: Cannot use CUDAPlace in CPU only version at [/home/teamcity/work/3f8ad9e2362c55ac/paddle/fluid/pybind/pybind.cc:806]
PaddlePaddle Call Stacks: 
0          0x10e7bc794p void paddle::platform::EnforceNotMet::Init<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*, int) + 628
1          0x10e7bc4c0p paddle::platform::EnforceNotMet::EnforceNotMet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int) + 80
2          0x10e81d5fap void pybind11::cpp_function::initialize<paddle::pybind::pybind11_init_core(pybind11::module&)::$_76, void, paddle::platform::CUDAPlace&, int, pybind11::name, pybind11::is_method, pybind11::sibling>(paddle::pybind::pybind11_init_core(pybind11::module&)::$_76&&, void (*)(paddle::platform::CUDAPlace&, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&) + 250
3          0x10e77f558p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
4          0x1025f9c55p PyObject_Call + 101
5          0x102609032p instancemethod_call + 162
6          0x1025f9c55p PyObject_Call + 101
7          0x10265ccdfp slot_tp_init + 175
8          0x102658ba9p type_call + 313
9          0x1025f9c55p PyObject_Call + 101
10         0x1026a6168p PyEval_EvalFrameEx + 22088
11         0x1026a08c4p PyEval_EvalCodeEx + 2164
12         0x1026a0042p PyEval_EvalCode + 34
13         0x1026cda7dp PyRun_FileExFlags + 157
14         0x1026cd5c0p PyRun_SimpleFileExFlags + 816
15         0x1026e4452p Py_Main + 3506
16      0x7fff6b242ed9p start + 1



FileName:l2_normalize.py:
---------------------------

successful


FileName:Preprocessor.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Preprocessor.py", line 4, in <module>
    preprocessor = fluid.layers.io.Preprocessor(reader=reader)
NameError: name 'reader' is not defined


FileName:mean_iou.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/mean_iou.py", line 4, in <module>
    iou, wrongs, corrects = fluid.layers.mean_iou(predict, label, num_classes)
NameError: name 'predict' is not defined


FileName:roi_pool.py:
---------------------------

  File "./api_codes/roi_pool.py", line 4
    pool_out = fluid.layers.roi_pool(input=x, rois=rois, 7, 7, 1.0)
SyntaxError: non-keyword arg after keyword arg


FileName:prior_box.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/prior_box.py", line 5, in <module>
    input=conv1,
NameError: name 'conv1' is not defined


FileName:grid_sampler.py:
---------------------------

  File "./api_codes/grid_sampler.py", line 6
    grid = fluid.layers.affine_grid(input=theta, size=[3, 10, 32, 32]})
                                                                     ^
SyntaxError: invalid syntax


FileName:multiclass_nms.py:
---------------------------

successful


FileName:IfElse.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/IfElse.py", line 5, in <module>
    input=label, dtype='int64', shape=[1], value=5.0)
NameError: name 'label' is not defined


FileName:multi_box_head.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/multi_box_head.py", line 5, in <module>
    inputs=[conv1, conv2, conv3, conv4, conv5, conv5],
NameError: name 'conv1' is not defined


FileName:sequence_softmax.py:
---------------------------

successful


FileName:DataFeedDesc.py:
---------------------------

  File "./api_codes/DataFeedDesc.py", line 4
    name: "MultiSlotDataFeed"
        ^
SyntaxError: invalid syntax


FileName:img_conv_group.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/img_conv_group.py", line 12, in <module>
    pool_stride=2)
TypeError: img_conv_group() got an unexpected keyword argument 'num_channels'


FileName:beam_search.py:
---------------------------

  File "./api_codes/beam_search.py", line 10
    y=layers.reshape(
    ^
IndentationError: unexpected indent


FileName:conv3d_transpose.py:
---------------------------

successful


FileName:Switch.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Switch.py", line 10, in <module>
    one_var = tensor.fill_constant(
NameError: name 'tensor' is not defined


FileName:generate_mask_labels.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/generate_mask_labels.py", line 11, in <module>
    for semgs in batch_semgs:
NameError: name 'batch_semgs' is not defined


FileName:sigmoid_cross_entropy_with_logits.py:
---------------------------

successful


FileName:chunk_eval_3.py:
---------------------------

  File "./api_codes/chunk_eval_3.py", line 4
    B-ORG  0
           ^
SyntaxError: invalid syntax


FileName:gru_unit.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/gru_unit.py", line 5, in <module>
    x_t = fluid.layers.fc(input=x_t_data, size=30)
NameError: name 'x_t_data' is not defined


FileName:WeightNormParamAttr.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/WeightNormParamAttr.py", line 7, in <module>
    param_attr=WeightNormParamAttr(
NameError: name 'WeightNormParamAttr' is not defined


FileName:array_length.py:
---------------------------

successful


FileName:While.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/While.py", line 4, in <module>
    d0 = layers.data("d0", shape=[10], dtype='float32')
NameError: name 'layers' is not defined


FileName:crop.py:
---------------------------

successful


FileName:log_loss.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/log_loss.py", line 4, in <module>
    prob = fluid.layers.sigmoid(net)
NameError: name 'net' is not defined


FileName:pool3d.py:
---------------------------

successful


FileName:exponential_decay_1.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/exponential_decay_1.py", line 4, in <module>
    if staircase == True:
NameError: name 'staircase' is not defined


FileName:start_profiler.py:
---------------------------


------------------------->     Profiling Report     <-------------------------

Place: CUDA
Time unit: ms
Sorted by total time in descending order in the same thread

EventCalls       Total       Min.        Max.        Ave.        Ratio.      

successful


FileName:hash.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/hash.py", line 4, in <module>
    word_dict = paddle.dataset.imdb.word_dict()
NameError: name 'paddle' is not defined


FileName:Executor. run_1.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Executor. run_1.py", line 4, in <module>
    cpu = core.CPUPlace()
NameError: name 'core' is not defined


FileName:pool2d.py:
---------------------------

successful


FileName:sequence_expand.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sequence_expand.py", line 7, in <module>
    out = layers.sequence_expand(x=x, y=y, ref_level=0)
NameError: name 'layers' is not defined


FileName:relu6.py:
---------------------------

successful


FileName:pad.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/pad.py", line 6, in <module>
    x=x, paddings=[0, 1, 1, 2], pad_value=0.)
NameError: name 'x' is not defined


FileName:DataFeeder_2.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DataFeeder_2.py", line 7, in <module>
    main_program.global_block().var(var_name) for var_name in feed_vars_name
NameError: name 'feed_vars_name' is not defined


FileName:chunk_eval_4.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/chunk_eval_4.py", line 5, in <module>
    input=hidden, label=label, param_attr=ParamAttr(name="crfw"))
NameError: name 'hidden' is not defined


FileName:smooth_l1.py:
---------------------------

successful


FileName:dynamic_lstmp.py:
---------------------------

successful


FileName:sequence_pool.py:
---------------------------

successful


FileName:save_params.py:
---------------------------

successful


FileName:Precision.py:
---------------------------

  File "./api_codes/Precision.py", line 5
    for pass in range(PASSES):
           ^
SyntaxError: invalid syntax


FileName:detection_map.py:
---------------------------

successful


FileName:ctc_greedy_decoder.py:
---------------------------

successful


FileName:anchor_generator.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/anchor_generator.py", line 4, in <module>
    anchor, var = anchor_generator(
NameError: name 'anchor_generator' is not defined


FileName:elementwise_sub.py:
---------------------------

  File "./api_codes/elementwise_sub.py", line 4
    shape(X) = (2, 3, 4, 5), shape(Y) = (,)
                                         ^
SyntaxError: invalid syntax


FileName:array_write.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/array_write.py", line 6, in <module>
    arr = layers.array_write(tmp, i=i)
NameError: name 'layers' is not defined


FileName:conv2d_transpose.py:
---------------------------

successful


FileName:hsigmoid.py:
---------------------------

With sparse mode, if your models has only small parameter prefetch may cause speed down
successful


FileName:DynamicRNN. memory_1.py:
---------------------------

successful


FileName:conv3d.py:
---------------------------

successful


FileName:DataFeedDesc. set_dense_slots.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DataFeedDesc. set_dense_slots.py", line 4, in <module>
    data_feed = fluid.DataFeedDesc('data.proto')
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/data_feed_desc.py", line 72, in __init__
    with open(proto_file, 'r') as f:
IOError: [Errno 2] No such file or directory: 'data.proto'


FileName:transpose.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/transpose.py", line 8, in <module>
    x_transposed = layers.transpose(x, perm=[1, 0, 2])
NameError: name 'layers' is not defined


FileName:density_prior_box.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/density_prior_box.py", line 5, in <module>
    input=conv1,
NameError: name 'conv1' is not defined


FileName:sums.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sums.py", line 6, in <module>
    a0 = layers.array_read(array=tmp, i=i)
NameError: name 'layers' is not defined


FileName:resize_nearest.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/resize_nearest.py", line 4, in <module>
    out = fluid.layers.resize_nearest(input, out_shape=[12, 12])
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 7410, in resize_nearest
    align_corners)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 7177, in image_resize
    dtype = helper.input_dtype()
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 95, in input_dtype
    dtype = each.dtype
AttributeError: 'NoneType' object has no attribute 'dtype'


FileName:conv2d.py:
---------------------------

successful


FileName:bilinear_tensor_product.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/bilinear_tensor_product.py", line 4, in <module>
    tensor = bilinear_tensor_product(x=layer1, y=layer2, size=1000)
NameError: name 'bilinear_tensor_product' is not defined


FileName:split.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/split.py", line 5, in <module>
    x0, x1, x2 = fluid.layers.split(x, num_or_sections=3, dim=1)
NameError: name 'x' is not defined


FileName:prelu.py:
---------------------------

successful


FileName:init_on_cpu.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/init_on_cpu.py", line 4, in <module>
    with init_on_cpu():
NameError: name 'init_on_cpu' is not defined


FileName:noam_decay.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/noam_decay.py", line 5, in <module>
    lr_value = np.power(d_model, -0.5) * np.min([
NameError: name 'd_model' is not defined


FileName:Print.py:
---------------------------

  File "./api_codes/Print.py", line 4
    value = some_layer(...)
                       ^
SyntaxError: invalid syntax


FileName:assign.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/assign.py", line 5, in <module>
    hidden = fluid.layers.fc(input=data, size=10)
NameError: name 'data' is not defined


FileName:reduce_prod.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/reduce_prod.py", line 8, in <module>
    fluid.layers.reduce_prod(x)  # [0.0002268]
NameError: name 'x' is not defined


FileName:scatter.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/scatter.py", line 4, in <module>
    output = fluid.layers.scatter(input, index, updates)
NameError: name 'index' is not defined


FileName:save_inference_model.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/save_inference_model.py", line 7, in <module>
    target_vars=[predict_var], executor=exe)
NameError: name 'predict_var' is not defined


FileName:one_hot.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/one_hot.py", line 4, in <module>
    label = layers.data(name="label", shape=[1], dtype="float32")
NameError: name 'layers' is not defined


FileName:sequence_slice.py:
---------------------------

successful


FileName:huber_loss_1.py:
---------------------------

  File "./api_codes/huber_loss_1.py", line 4
    huber\_loss = delta * (label - input) - 0.5 * delta * delta
                                                              ^
SyntaxError: unexpected character after line continuation character


FileName:add_position_encoding.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/add_position_encoding.py", line 4, in <module>
    position_tensor = fluid.layers.add_position_encoding(input=tensor)
NameError: name 'tensor' is not defined


FileName:multiplex.py:
---------------------------

successful


FileName:image_resize.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/image_resize.py", line 4, in <module>
    out = fluid.layers.image_resize(input, out_shape=[12, 12], resample="NEAREST")
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 7177, in image_resize
    dtype = helper.input_dtype()
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 95, in input_dtype
    dtype = each.dtype
AttributeError: 'NoneType' object has no attribute 'dtype'


FileName:ChunkEvaluator.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/ChunkEvaluator.py", line 5, in <module>
    data = fluid.layers.data(name="data", shape=[32, 32], dtype="int32")
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 100, in data
    is_data=True)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py", line 353, in create_global_variable
    *args, persistable=persistable, **kwargs)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1526, in create_var
    var = Variable(block=self, *args, **kwargs)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 440, in __init__
    "matched.".format(self.name, old_shape, shape))
ValueError: Variable data has been created before. the previous shape is (-1L, 1L); the new shape is (-1, 32, 32). They are not matched.


FileName:relu.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/relu.py", line 4, in <module>
    output = fluid.layers.relu(x)
NameError: name 'x' is not defined


FileName:chunk_eval_1.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/chunk_eval_1.py", line 4, in <module>
    tag_type = label % num_tag_type
NameError: name 'label' is not defined


FileName:warpctc.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/warpctc.py", line 4, in <module>
    label = fluid.layers.data(shape=[11, 8], dtype='float32', lod_level=1)
TypeError: data() takes at least 2 arguments (3 given)


FileName:py_reader.py:
---------------------------

  File "./api_codes/py_reader.py", line 10
    img, label = fluid.layers.read_file(reader)
      ^
SyntaxError: invalid syntax


FileName:UniformInitializer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/UniformInitializer.py", line 4, in <module>
    fc = fluid.layers.fc(input=x, size=10,
NameError: name 'x' is not defined


FileName:swish.py:
---------------------------

successful


FileName:ParallelExecutor. run_2.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/ParallelExecutor. run_2.py", line 4, in <module>
    exe = ParallelExecutor()
NameError: name 'ParallelExecutor' is not defined


FileName:force_init_on_cpu.py:
---------------------------

  File "./api_codes/force_init_on_cpu.py", line 5
    create_op('force_cpu': force_init_on_cpu())
                         ^
SyntaxError: invalid syntax


FileName:load_params.py:
---------------------------

successful


FileName:soft_relu.py:
---------------------------

successful


FileName:DataFeedDesc. set_batch_size.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DataFeedDesc. set_batch_size.py", line 4, in <module>
    data_feed = fluid.DataFeedDesc('data.proto')
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/data_feed_desc.py", line 72, in __init__
    with open(proto_file, 'r') as f:
IOError: [Errno 2] No such file or directory: 'data.proto'


FileName:unsqueeze.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/unsqueeze.py", line 4, in <module>
    x = layers.data(name='x', shape=[5, 10])
NameError: name 'layers' is not defined


FileName:hard_shrink.py:
---------------------------

successful


FileName:elementwise_mul.py:
---------------------------

  File "./api_codes/elementwise_mul.py", line 4
    shape(X) = (2, 3, 4, 5), shape(Y) = (,)
                                         ^
SyntaxError: invalid syntax


FileName:Program.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Program.py", line 9, in <module>
    fluid.layers.fc(name="fc", shape=[10], dtype='float32', act="relu")
TypeError: fc() got an unexpected keyword argument 'shape'


FileName:create_array.py:
---------------------------

successful


FileName:elementwise_min.py:
---------------------------

  File "./api_codes/elementwise_min.py", line 4
    shape(X) = (2, 3, 4, 5), shape(Y) = (,)
                                         ^
SyntaxError: invalid syntax


FileName:label_smooth.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/label_smooth.py", line 4, in <module>
    label = layers.data(name="label", shape=[1], dtype="float32")
NameError: name 'layers' is not defined


FileName:stanh.py:
---------------------------

successful


FileName:DataFeeder_1(1).py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DataFeeder_1(1).py", line 4, in <module>
    place=fluid.CUDAPlace(0)
paddle.fluid.core.EnforceNotMet: Cannot use CUDAPlace in CPU only version at [/home/teamcity/work/3f8ad9e2362c55ac/paddle/fluid/pybind/pybind.cc:806]
PaddlePaddle Call Stacks: 
0          0x11a774794p void paddle::platform::EnforceNotMet::Init<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*, int) + 628
1          0x11a7744c0p paddle::platform::EnforceNotMet::EnforceNotMet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int) + 80
2          0x11a7d55fap void pybind11::cpp_function::initialize<paddle::pybind::pybind11_init_core(pybind11::module&)::$_76, void, paddle::platform::CUDAPlace&, int, pybind11::name, pybind11::is_method, pybind11::sibling>(paddle::pybind::pybind11_init_core(pybind11::module&)::$_76&&, void (*)(paddle::platform::CUDAPlace&, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&) + 250
3          0x11a737558p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
4          0x10e5aac55p PyObject_Call + 101
5          0x10e5ba032p instancemethod_call + 162
6          0x10e5aac55p PyObject_Call + 101
7          0x10e60dcdfp slot_tp_init + 175
8          0x10e609ba9p type_call + 313
9          0x10e5aac55p PyObject_Call + 101
10         0x10e657168p PyEval_EvalFrameEx + 22088
11         0x10e6518c4p PyEval_EvalCodeEx + 2164
12         0x10e651042p PyEval_EvalCode + 34
13         0x10e67ea7dp PyRun_FileExFlags + 157
14         0x10e67e5c0p PyRun_SimpleFileExFlags + 816
15         0x10e695452p Py_Main + 3506
16      0x7fff6b242ed9p start + 1



FileName:edit_distance.py:
---------------------------

successful


FileName:dynamic_gru.py:
---------------------------

successful


FileName:program_guard.py:
---------------------------

  File "./api_codes/program_guard.py", line 5
    data = fluid.layers.data(...)
                             ^
SyntaxError: invalid syntax


FileName:AdamaxOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/AdamaxOptimizer.py", line 5, in <module>
    optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:piecewise_decay.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/piecewise_decay.py", line 6, in <module>
    if step < 10000:
NameError: name 'step' is not defined


FileName:shape.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/shape.py", line 4, in <module>
    input = layers.data(
NameError: name 'layers' is not defined


FileName:affine_grid.py:
---------------------------

successful


FileName:Program. clone.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Program. clone.py", line 6, in <module>
    optimizer.minimize()
TypeError: minimize() takes at least 2 arguments (1 given)


FileName:scaled_dot_product_attention.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/scaled_dot_product_attention.py", line 19, in <module>
    contexts = fluid.nets.scaled_dot_product_attention(queries, keys, values)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/nets.py", line 525, in scaled_dot_product_attention
    ctx_multiheads = layers.matmul(weights, v)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 4923, in matmul
    __check_input(x, y)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 4912, in __check_input
    (x_shape, y_shape))
ValueError: Invalid inputs for matmul. x: [3L, 6L, 5L], y: [3L, 6L, 10L]



FileName:AdamOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/AdamOptimizer.py", line 5, in <module>
    optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:ParallelExecutor. run.py:
---------------------------

  File "./api_codes/ParallelExecutor. run.py", line 8
    fetch_list=[avg_cost.name]))
                               ^
SyntaxError: invalid syntax


FileName:random_data_generator.py:
---------------------------

successful


FileName:stop_profiler.py:
---------------------------


------------------------->     Profiling Report     <-------------------------

Place: CUDA
Time unit: ms
Sorted by total time in descending order in the same thread

EventCalls       Total       Min.        Max.        Ave.        Ratio.      

successful


FileName:sequence_reshape.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sequence_reshape.py", line 4, in <module>
    x = fluid.layers.data(shape=[5, 20], dtype='float32', lod_level=1)
TypeError: data() takes at least 2 arguments (3 given)


FileName:NormalInitializer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/NormalInitializer.py", line 4, in <module>
    fc = fluid.layers.fc(input=x, size=10,
NameError: name 'x' is not defined


FileName:ParamAttr.py:
---------------------------

successful


FileName:dropout.py:
---------------------------

successful


FileName:roi_perspective_transform.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/roi_perspective_transform.py", line 4, in <module>
    out = fluid.layers.roi_perspective_transform(input, rois, 7, 7, 1.0)
NameError: name 'rois' is not defined


FileName:sum.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sum.py", line 4, in <module>
    input = layers.data(name="input", shape=[13, 11], dtype='float32')
NameError: name 'layers' is not defined


FileName:simple_img_conv_pool.py:
---------------------------

successful


FileName:less_than.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/less_than.py", line 2, in <module>
    less = fluid.layers.less_than(x=label, y=limit)
NameError: name 'label' is not defined


FileName:rpn_target_assign.py:
---------------------------

  File "./api_codes/rpn_target_assign.py", line 12
    loc_pred, score_pred, loc_target, score_target, bbox_inside_weight =
                                                                       ^
SyntaxError: invalid syntax


FileName:read_file.py:
---------------------------

  File "./api_codes/read_file.py", line 9
    data_file = fluid.layers.double_buffer(
    ^
IndentationError: unexpected indent


FileName:Program. clone_2.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Program. clone_2.py", line 20, in <module>
    sgd.minimize(loss)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 487, in minimize
    no_grad_set=no_grad_set)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 392, in backward
    no_grad_set, callbacks)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/backward.py", line 518, in append_backward
    _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/backward.py", line 354, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected dy_dims.size() == rank, but received dy_dims.size():1 != rank:2.
Input(Y@Grad) and Input(X) should have the same rank. at [/home/teamcity/work/3f8ad9e2362c55ac/paddle/fluid/operators/cross_entropy_op.cc:98]
PaddlePaddle Call Stacks: 
0          0x10c474794p void paddle::platform::EnforceNotMet::Init<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*, int) + 628
1          0x10c4744c0p paddle::platform::EnforceNotMet::EnforceNotMet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int) + 80
2          0x10cb80f23p paddle::operators::CrossEntropyGradientOpBase::InferShape(paddle::framework::InferShapeContext*) const + 2963
3          0x10cb864c3p paddle::operators::CrossEntropyGradientOp2::InferShape(paddle::framework::InferShapeContext*) const + 99
4          0x10c5c03f8p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 1464
5          0x10c533506p void pybind11::cpp_function::initialize<pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void&&, paddle::framework::OpDesc (*)(paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 198
6          0x10c437558p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
7          0x100358297p PyEval_EvalFrameEx + 22391
8          0x1003528c4p PyEval_EvalCodeEx + 2164
9          0x10035cc0dp fast_function + 109
10         0x100357f89p PyEval_EvalFrameEx + 21609
11         0x1003528c4p PyEval_EvalCodeEx + 2164
12         0x10035cc0dp fast_function + 109
13         0x100357f89p PyEval_EvalFrameEx + 21609
14         0x1003528c4p PyEval_EvalCodeEx + 2164
15         0x10035cc0dp fast_function + 109
16         0x100357f89p PyEval_EvalFrameEx + 21609
17         0x1003528c4p PyEval_EvalCodeEx + 2164
18         0x10035cc0dp fast_function + 109
19         0x100357f89p PyEval_EvalFrameEx + 21609
20         0x1003528c4p PyEval_EvalCodeEx + 2164
21         0x100352042p PyEval_EvalCode + 34
22         0x10037fa7dp PyRun_FileExFlags + 157
23         0x10037f5c0p PyRun_SimpleFileExFlags + 816
24         0x100396452p Py_Main + 3506
25      0x7fff6b242ed9p start + 1



FileName:inverse_time_decay.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/inverse_time_decay.py", line 11, in <module>
    sgd_optimizer.minimize(avg_cost)
NameError: name 'avg_cost' is not defined


FileName:cumsum.py:
---------------------------

successful


FileName:DynamicRNN.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DynamicRNN.py", line 2, in <module>
    data = fluid.layers.data(name='sentence', dtype='int64', lod_level=1)
TypeError: data() takes at least 2 arguments (3 given)


FileName:brelu.py:
---------------------------

successful


FileName:thresholded_relu.py:
---------------------------

successful


FileName:Accuracy.py:
---------------------------

  File "./api_codes/Accuracy.py", line 9
    for pass in range(PASSES):
           ^
SyntaxError: invalid syntax


FileName:nce.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/nce.py", line 7, in <module>
    words.append(layers.data(
NameError: name 'layers' is not defined


FileName:FtrlOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/FtrlOptimizer.py", line 5, in <module>
    _, params_grads = optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:sequence_unpad.py:
---------------------------

successful


FileName:lstm.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/lstm.py", line 4, in <module>
    input = embedding
NameError: name 'embedding' is not defined


FileName:create_parameter.py:
---------------------------

successful


FileName:load.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/load.py", line 3, in <module>
    fluid.layers.load(tmp_tensor, "./tmp_tensor.bin")
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 1216, in load
    helper.append_op(type="load", inputs={}, output={"Out": out}, args=attrs)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1662, in append_op
    attrs=kwargs.get("attrs", None))
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1066, in __init__
    self.desc.check_attrs()
paddle.fluid.core.EnforceNotMet: Attribute 'file_path' is required! at [/home/teamcity/work/3f8ad9e2362c55ac/paddle/fluid/framework/attribute.h:276]
PaddlePaddle Call Stacks: 
0          0x1147016ecp void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 636
1          0x11470141bp paddle::platform::EnforceNotMet::EnforceNotMet(std::exception_ptr, char const*, int) + 139
2          0x1151d8929p paddle::framework::TypedAttrChecker<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::operator()(std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, boost::variant<boost::blank, int, float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, bool, std::__1::vector<bool, std::__1::allocator<bool> >, paddle::framework::BlockDesc*, long long, std::__1::vector<paddle::framework::BlockDesc*, std::__1::allocator<paddle::framework::BlockDesc*> >, std::__1::vector<long long, std::__1::allocator<long long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, boost::variant<boost::blank, int, float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, bool, std::__1::vector<bool, std::__1::allocator<bool> >, paddle::framework::BlockDesc*, long long, std::__1::vector<paddle::framework::BlockDesc*, std::__1::allocator<paddle::framework::BlockDesc*> >, std::__1::vector<long long, std::__1::allocator<long long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >*) const + 553
3          0x114851ca6p paddle::framework::OpDesc::CheckAttrs() + 358
4          0x1147c528bp void pybind11::cpp_function::initialize<pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(paddle::framework::OpDesc*), void, paddle::framework::OpDesc*, pybind11::name, pybind11::is_method, pybind11::sibling>(void&&, paddle::framework::OpDesc (*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&) + 107
5          0x1146c9558p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
6          0x1085de297p PyEval_EvalFrameEx + 22391
7          0x1085d88c4p PyEval_EvalCodeEx + 2164
8          0x10855a723p function_call + 355
9          0x108531c55p PyObject_Call + 101
10         0x108541032p instancemethod_call + 162
11         0x108531c55p PyObject_Call + 101
12         0x108594cdfp slot_tp_init + 175
13         0x108590ba9p type_call + 313
14         0x108531c55p PyObject_Call + 101
15         0x1085de168p PyEval_EvalFrameEx + 22088
16         0x1085d88c4p PyEval_EvalCodeEx + 2164
17         0x10855a723p function_call + 355
18         0x108531c55p PyObject_Call + 101
19         0x1085df1f0p PyEval_EvalFrameEx + 26320
20         0x1085d88c4p PyEval_EvalCodeEx + 2164
21         0x1085e2c0dp fast_function + 109
22         0x1085ddf89p PyEval_EvalFrameEx + 21609
23         0x1085d88c4p PyEval_EvalCodeEx + 2164
24         0x1085e2c0dp fast_function + 109
25         0x1085ddf89p PyEval_EvalFrameEx + 21609
26         0x1085d88c4p PyEval_EvalCodeEx + 2164
27         0x1085d8042p PyEval_EvalCode + 34
28         0x108605a7dp PyRun_FileExFlags + 157
29         0x1086055c0p PyRun_SimpleFileExFlags + 816
30         0x10861c452p Py_Main + 3506
31      0x7fff6b242ed9p start + 1
32                 0x2p



FileName:reduce_max.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/reduce_max.py", line 8, in <module>
    fluid.layers.reduce_max(x)  # [0.9]
NameError: name 'x' is not defined


FileName:sampling_id.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sampling_id.py", line 4, in <module>
    x = layers.data(
NameError: name 'layers' is not defined


FileName:uniform_random.py:
---------------------------

successful


FileName:clip.py:
---------------------------

successful


FileName:elu.py:
---------------------------

successful


FileName:ConstantInitializer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/ConstantInitializer.py", line 4, in <module>
    fc = fluid.layers.fc(input=x, size=10,
NameError: name 'x' is not defined


FileName:append_LARS.py:
---------------------------

  File "./api_codes/append_LARS.py", line 5
    / (sqrt(sumsq(gradient))+ weight_decay * sqrt(sumsq(param)))
    ^
IndentationError: unexpected indent


FileName:profiler.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/profiler.py", line 7, in <module>
    for pass_id in range(pass_num):
NameError: name 'pass_num' is not defined


FileName:topk.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/topk.py", line 4, in <module>
    top5_values, top5_indices = layers.topk(input, k=5)
NameError: name 'layers' is not defined


FileName:batch_norm.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/batch_norm.py", line 4, in <module>
    hidden1 = fluid.layers.fc(input=x, size=200, param_attr='fc1.w')
NameError: name 'x' is not defined


FileName:reset_profiler.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/reset_profiler.py", line 5, in <module>
    with profiler.profiler(state, 'total', '/tmp/profile'):
NameError: name 'state' is not defined


FileName:logical_or.py:
---------------------------

successful


FileName:squeeze.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/squeeze.py", line 4, in <module>
    x = layers.data(name='x', shape=[5, 1, 10])
NameError: name 'layers' is not defined


FileName:TruncatedNormalInitializer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/TruncatedNormalInitializer.py", line 4, in <module>
    fc = fluid.layers.fc(input=x, size=10,
NameError: name 'x' is not defined


FileName:softmax_with_cross_entropy.py:
---------------------------

successful


FileName:double_buffer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/double_buffer.py", line 6, in <module>
    dtypes=['float32', 'int64'])
TypeError: open_files() takes at least 4 arguments (3 given)


FileName:exponential_decay.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/exponential_decay.py", line 11, in <module>
    sgd_optimizer.minimize(avg_cost)
NameError: name 'avg_cost' is not defined


FileName:DataFeeder.py:
---------------------------

successful


FileName:natural_exp_decay.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/natural_exp_decay.py", line 4, in <module>
    if not staircase:
NameError: name 'staircase' is not defined


FileName:yolov3_loss.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/yolov3_loss.py", line 11, in <module>
    ignore_thresh=0.7, downsample_ratio=32)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/detection.py", line 628, in yolov3_loss
    attrs=attrs)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1662, in append_op
    attrs=kwargs.get("attrs", None))
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1069, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected dim_gtbox[2] == 4, but received dim_gtbox[2]:5 != 4:4.
Input(GTBox) dim[2] should be 5 at [/home/teamcity/work/3f8ad9e2362c55ac/paddle/fluid/operators/detection/yolov3_loss_op.cc:57]
PaddlePaddle Call Stacks: 
0          0x1156ac794p void paddle::platform::EnforceNotMet::Init<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*, int) + 628
1          0x1156ac4c0p paddle::platform::EnforceNotMet::EnforceNotMet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int) + 80
2          0x11640dac3p paddle::operators::Yolov3LossOp::InferShape(paddle::framework::InferShapeContext*) const + 4163
3          0x1157f83f8p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 1464
4          0x11576b506p void pybind11::cpp_function::initialize<pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void&&, paddle::framework::OpDesc (*)(paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 198
5          0x11566f558p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
6          0x1092d9297p PyEval_EvalFrameEx + 22391
7          0x1092d38c4p PyEval_EvalCodeEx + 2164
8          0x109255723p function_call + 355
9          0x10922cc55p PyObject_Call + 101
10         0x10923c032p instancemethod_call + 162
11         0x10922cc55p PyObject_Call + 101
12         0x10928fcdfp slot_tp_init + 175
13         0x10928bba9p type_call + 313
14         0x10922cc55p PyObject_Call + 101
15         0x1092d9168p PyEval_EvalFrameEx + 22088
16         0x1092d38c4p PyEval_EvalCodeEx + 2164
17         0x109255723p function_call + 355
18         0x10922cc55p PyObject_Call + 101
19         0x1092da1f0p PyEval_EvalFrameEx + 26320
20         0x1092d38c4p PyEval_EvalCodeEx + 2164
21         0x1092ddc0dp fast_function + 109
22         0x1092d8f89p PyEval_EvalFrameEx + 21609
23         0x1092d38c4p PyEval_EvalCodeEx + 2164
24         0x1092ddc0dp fast_function + 109
25         0x1092d8f89p PyEval_EvalFrameEx + 21609
26         0x1092d38c4p PyEval_EvalCodeEx + 2164
27         0x1092d3042p PyEval_EvalCode + 34
28         0x109300a7dp PyRun_FileExFlags + 157
29         0x1093005c0p PyRun_SimpleFileExFlags + 816
30         0x109317452p Py_Main + 3506
31      0x7fff6b242ed9p start + 1



FileName:Executor. run(1).py:
---------------------------

  File "./api_codes/Executor. run(1).py", line 10
    >>> adam.minimize(loss)
    ^
IndentationError: unexpected indent


FileName:softmax.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/softmax.py", line 4, in <module>
    fc = fluid.layers.fc(input=x, size=10)
NameError: name 'x' is not defined


FileName:GradientClipByGlobalNorm.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/GradientClipByGlobalNorm.py", line 4, in <module>
    p_g_clip = fluid.backward.append_backward(loss=avg_cost_clip)
NameError: name 'avg_cost_clip' is not defined


FileName:AdagradOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/AdagradOptimizer.py", line 5, in <module>
    optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:GradientClipByNorm.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/GradientClipByNorm.py", line 4, in <module>
    w_param_attrs = flui.ParamAttr(name=None,
NameError: name 'flui' is not defined


FileName:DataFeeder(1).py:
---------------------------

successful


FileName:expand.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/expand.py", line 5, in <module>
    out = fluid.layers.expand(x=x, expand_times=[1, 2, 2])
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 8902, in expand
    attrs={'expand_times': expand_times})
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1662, in append_op
    attrs=kwargs.get("attrs", None))
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1069, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected static_cast<size_t>(x_dims.size()) == expand_times.size(), but received static_cast<size_t>(x_dims.size()):2 != expand_times.size():3.
The number of Attr(expand_times)'s value must be equal to the rank of Input(X). at [/home/teamcity/work/3f8ad9e2362c55ac/paddle/fluid/operators/expand_op.cc:39]
PaddlePaddle Call Stacks: 
0          0x111958794p void paddle::platform::EnforceNotMet::Init<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*, int) + 628
1          0x1119584c0p paddle::platform::EnforceNotMet::EnforceNotMet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int) + 80
2          0x111ef90f9p paddle::operators::ExpandOp::InferShape(paddle::framework::InferShapeContext*) const + 1497
3          0x111aa43f8p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 1464
4          0x111a17506p void pybind11::cpp_function::initialize<pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void&&, paddle::framework::OpDesc (*)(paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 198
5          0x11191b558p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
6          0x105842297p PyEval_EvalFrameEx + 22391
7          0x10583c8c4p PyEval_EvalCodeEx + 2164
8          0x1057be723p function_call + 355
9          0x105795c55p PyObject_Call + 101
10         0x1057a5032p instancemethod_call + 162
11         0x105795c55p PyObject_Call + 101
12         0x1057f8cdfp slot_tp_init + 175
13         0x1057f4ba9p type_call + 313
14         0x105795c55p PyObject_Call + 101
15         0x105842168p PyEval_EvalFrameEx + 22088
16         0x10583c8c4p PyEval_EvalCodeEx + 2164
17         0x1057be723p function_call + 355
18         0x105795c55p PyObject_Call + 101
19         0x1058431f0p PyEval_EvalFrameEx + 26320
20         0x10583c8c4p PyEval_EvalCodeEx + 2164
21         0x105846c0dp fast_function + 109
22         0x105841f89p PyEval_EvalFrameEx + 21609
23         0x10583c8c4p PyEval_EvalCodeEx + 2164
24         0x105846c0dp fast_function + 109
25         0x105841f89p PyEval_EvalFrameEx + 21609
26         0x10583c8c4p PyEval_EvalCodeEx + 2164
27         0x10583c042p PyEval_EvalCode + 34
28         0x105869a7dp PyRun_FileExFlags + 157
29         0x1058695c0p PyRun_SimpleFileExFlags + 816
30         0x105880452p Py_Main + 3506
31      0x7fff6b242ed9p start + 1
32                 0x2p



FileName:reduce_mean.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/reduce_mean.py", line 8, in <module>
    fluid.layers.reduce_mean(x)  # [0.4375]
NameError: name 'x' is not defined


FileName:random_crop.py:
---------------------------

successful


FileName:open_files.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/open_files.py", line 8, in <module>
    dtypes=['float32', 'int64'])
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 901, in open_files
    shape_concat.extend(shape)
TypeError: 'int' object is not iterable


FileName:DataFeedDesc. set_use_slots.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DataFeedDesc. set_use_slots.py", line 4, in <module>
    data_feed = fluid.DataFeedDesc('data.proto')
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/data_feed_desc.py", line 72, in __init__
    with open(proto_file, 'r') as f:
IOError: [Errno 2] No such file or directory: 'data.proto'


FileName:data.py:
---------------------------

successful


FileName:DataFeeder_2(1).py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DataFeeder_2(1).py", line 7, in <module>
    main_program.global_block().var(var_name) for var_name in feed_vars_name
NameError: name 'feed_vars_name' is not defined


FileName:similarity_focus.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/similarity_focus.py", line 6, in <module>
    x = fluid.layers.layer_norm(input=data, axis=1, indexes=[0])
TypeError: layer_norm() got an unexpected keyword argument 'axis'


FileName:CompositeMetric.py:
---------------------------

  File "./api_codes/CompositeMetric.py", line 12
    for pass in range(PASSES):
           ^
SyntaxError: invalid syntax


FileName:layer_norm.py:
---------------------------

successful


FileName:adaptive_pool2d.py:
---------------------------

successful


FileName:ones.py:
---------------------------

successful


FileName:crf_decoding.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/crf_decoding.py", line 4, in <module>
    crf_decode = layers.crf_decoding(
NameError: name 'layers' is not defined


FileName:XavierInitializer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/XavierInitializer.py", line 5, in <module>
    input=queries, size=10,
NameError: name 'queries' is not defined


FileName:selu.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/selu.py", line 4, in <module>
    output = fluid.layers.selu(x)
NameError: name 'x' is not defined


FileName:save_vars.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/save_vars.py", line 13, in <module>
    fluid.io.save_vars(executor=exe, dirname=path, main_program=prog,
NameError: name 'path' is not defined


FileName:adaptive_pool3d.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/adaptive_pool3d.py", line 27, in <module>
    pool_type='avg')
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 2906, in adaptive_pool3d
    "adaptive": True,
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1662, in append_op
    attrs=kwargs.get("attrs", None))
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1069, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Input size and pooling size should be consistent. at [/home/teamcity/work/3f8ad9e2362c55ac/paddle/fluid/operators/pool_op.cc:70]
PaddlePaddle Call Stacks: 
0          0x11a63a6ecp void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 636
1          0x11a63a41bp paddle::platform::EnforceNotMet::EnforceNotMet(std::exception_ptr, char const*, int) + 139
2          0x11a99b4bcp paddle::operators::PoolOp::InferShape(paddle::framework::InferShapeContext*) const + 3260
3          0x11a78b3f8p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 1464
4          0x11a6fe506p void pybind11::cpp_function::initialize<pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void&&, paddle::framework::OpDesc (*)(paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 198
5          0x11a602558p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
6          0x10e52b297p PyEval_EvalFrameEx + 22391
7          0x10e5258c4p PyEval_EvalCodeEx + 2164
8          0x10e4a7723p function_call + 355
9          0x10e47ec55p PyObject_Call + 101
10         0x10e48e032p instancemethod_call + 162
11         0x10e47ec55p PyObject_Call + 101
12         0x10e4e1cdfp slot_tp_init + 175
13         0x10e4ddba9p type_call + 313
14         0x10e47ec55p PyObject_Call + 101
15         0x10e52b168p PyEval_EvalFrameEx + 22088
16         0x10e5258c4p PyEval_EvalCodeEx + 2164
17         0x10e4a7723p function_call + 355
18         0x10e47ec55p PyObject_Call + 101
19         0x10e52c1f0p PyEval_EvalFrameEx + 26320
20         0x10e5258c4p PyEval_EvalCodeEx + 2164
21         0x10e52fc0dp fast_function + 109
22         0x10e52af89p PyEval_EvalFrameEx + 21609
23         0x10e5258c4p PyEval_EvalCodeEx + 2164
24         0x10e52fc0dp fast_function + 109
25         0x10e52af89p PyEval_EvalFrameEx + 21609
26         0x10e5258c4p PyEval_EvalCodeEx + 2164
27         0x10e525042p PyEval_EvalCode + 34
28         0x10e552a7dp PyRun_FileExFlags + 157
29         0x10e5525c0p PyRun_SimpleFileExFlags + 816
30         0x10e569452p Py_Main + 3506
31      0x7fff6b242ed9p start + 1



FileName:Auc.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Auc.py", line 4, in <module>
    pred = fluid.layers.fc(input=data, size=1000, act="tanh")
NameError: name 'data' is not defined


FileName:argmin.py:
---------------------------

  File "./api_codes/argmin.py", line 4
    out = fluid.layers.argmin(x=in, axis=0)
                                 ^
SyntaxError: invalid syntax


FileName:is_empty.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/is_empty.py", line 4, in <module>
    res = fluid.layers.is_empty(x=input)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layers/control_flow.py", line 1826, in is_empty
    type='is_empty', inputs={'X': [x]}, outputs={'Out': [cond]})
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1662, in append_op
    attrs=kwargs.get("attrs", None))
  File "/Users/shanyi01/anaconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1024, in __init__
    in_arg_names.append(cpt.to_text(arg.name))
AttributeError: 'builtin_function_or_method' object has no attribute 'name'
