

FileName:conv2d_transpose.py:
---------------------------

successful


FileName:ones.py:
---------------------------

successful


FileName:rank_loss.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/rank_loss.py", line 10, in <module>
    out = fluid.layers.rank_loss(label, left, right)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 8122, in rank_loss
    outputs={'Out': out})
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1663, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1070, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: All inputs must be 2-D tensors with shape [batch_size x 1]. at [/home/users/dongdaxiang/github_develop/Paddle/paddle/fluid/operators/rank_loss_op.cc:43]
PaddlePaddle Call Stacks: 
0       0x7f19b5bc9510p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f19b5bc9889p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f19b648cc99p paddle::operators::RankLossOp::InferShape(paddle::framework::InferShapeContext*) const + 729
3       0x7f19b5d2548ep paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 862
4       0x7f19b5c7adfcp
5       0x7f19b5bfc804p
6       0x7f1ab366abb8p PyEval_EvalFrameEx + 25016
7       0x7f1ab366e0bdp PyEval_EvalCodeEx + 2061
8       0x7f1ab35e4f85p
9       0x7f1ab35b2df3p PyObject_Call + 67
10      0x7f1ab35c19cdp
11      0x7f1ab35b2df3p PyObject_Call + 67
12      0x7f1ab3620bafp
13      0x7f1ab361d46fp
14      0x7f1ab35b2df3p PyObject_Call + 67
15      0x7f1ab36684a6p PyEval_EvalFrameEx + 15014
16      0x7f1ab366e0bdp PyEval_EvalCodeEx + 2061
17      0x7f1ab35e4f85p
18      0x7f1ab35b2df3p PyObject_Call + 67
19      0x7f1ab3667f97p PyEval_EvalFrameEx + 13719
20      0x7f1ab366e0bdp PyEval_EvalCodeEx + 2061
21      0x7f1ab366b345p PyEval_EvalFrameEx + 26949
22      0x7f1ab366e0bdp PyEval_EvalCodeEx + 2061
23      0x7f1ab366b345p PyEval_EvalFrameEx + 26949
24      0x7f1ab366e0bdp PyEval_EvalCodeEx + 2061
25      0x7f1ab366e1f2p PyEval_EvalCode + 50
26      0x7f1ab3696f42p PyRun_FileExFlags + 146
27      0x7f1ab36982d9p PyRun_SimpleFileExFlags + 217
28      0x7f1ab36ae00dp Py_Main + 3149
29      0x7f1ab28abbd5p __libc_start_main + 245
30            0x4007a1p



FileName:zeros.py:
---------------------------

successful


FileName:log_loss.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/log_loss.py", line 7, in <module>
    prob = fluid.layers.sigmoid(net)
NameError: name 'net' is not defined




FileName:generate_mask_labels_1.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/generate_mask_labels_1.py", line 22, in <module>
    rois=rois,
NameError: name 'rois' is not defined


FileName:argmin.py:
---------------------------

  File "./api_codes/argmin.py", line 7
    out = fluid.layers.argmin(x=in, axis=0)
                                 ^
SyntaxError: invalid syntax


FileName:conv3d_transpose.py:
---------------------------

successful


FileName:ParallelExecutor. run_1.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/ParallelExecutor. run_1.py", line 7, in <module>
    exe = ParallelExecutor()
NameError: name 'ParallelExecutor' is not defined


FileName:batch.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/batch.py", line 13, in <module>
    buffer_size=2)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 901, in open_files
    shape_concat.extend(shape)
TypeError: 'int' object is not iterable


FileName:DataFeeder_2.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DataFeeder_2.py", line 10, in <module>
    main_program.global_block().var(var_name) for var_name in feed_vars_name
NameError: name 'feed_vars_name' is not defined


FileName:sequence_first_step.py:
---------------------------

successful


FileName:roi_pool.py:
---------------------------

  File "./api_codes/roi_pool.py", line 7
    pool_out = fluid.layers.roi_pool(input=x, rois=rois, 7, 7, 1.0)
SyntaxError: non-keyword arg after keyword arg


FileName:Executor. run(1).py:
---------------------------

  File "./api_codes/Executor. run(1).py", line 13
    >>> adam.minimize(loss)
    ^
IndentationError: unexpected indent


FileName:polynomial_decay.py:
---------------------------

  File "./api_codes/polynomial_decay.py", line 11
    decayed_learning_rate = (learning_rate - end_learning_rate) *
                                                                ^
SyntaxError: invalid syntax


FileName:stop_profiler.py:
---------------------------


------------------------->     Profiling Report     <-------------------------

Place: CUDA
Time unit: ms
Sorted by total time in descending order in the same thread

EventCalls       Total       Min.        Max.        Ave.        Ratio.      

successful


FileName:lstm_unit.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/lstm_unit.py", line 7, in <module>
    x_t = fluid.layers.fc(input=x_t_data, size=10)
NameError: name 'x_t_data' is not defined


FileName:sequence_pad.py:
---------------------------

successful


FileName:double_buffer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/double_buffer.py", line 9, in <module>
    dtypes=['float32', 'int64'])
TypeError: open_files() takes at least 4 arguments (3 given)


FileName:density_prior_box.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/density_prior_box.py", line 8, in <module>
    input=conv1,
NameError: name 'conv1' is not defined


FileName:hsigmoid.py:
---------------------------

With sparse mode, if your models has only small parameter prefetch may cause speed down
successful


FileName:elementwise_div.py:
---------------------------

  File "./api_codes/elementwise_div.py", line 7
    shape(X) = (2, 3, 4, 5), shape(Y) = (,)
                                         ^
SyntaxError: invalid syntax


FileName:cross_entropy.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/cross_entropy.py", line 7, in <module>
    predict = fluid.layers.fc(input=net, size=classdim, act='softmax')
NameError: name 'net' is not defined


FileName:AdamOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/AdamOptimizer.py", line 8, in <module>
    optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:resize_nearest.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/resize_nearest.py", line 7, in <module>
    out = fluid.layers.resize_nearest(input, out_shape=[12, 12])
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 7441, in resize_nearest
    align_corners)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 7208, in image_resize
    dtype = helper.input_dtype()
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 95, in input_dtype
    dtype = each.dtype
AttributeError: 'NoneType' object has no attribute 'dtype'


FileName:argmax.py:
---------------------------

  File "./api_codes/argmax.py", line 7
    out = fluid.layers.argmax(x=in, axis=0)
                                 ^
SyntaxError: invalid syntax


FileName:detection_map.py:
---------------------------

successful


FileName:batch_norm.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/batch_norm.py", line 7, in <module>
    hidden1 = fluid.layers.fc(input=x, size=200, param_attr='fc1.w')
NameError: name 'x' is not defined


FileName:is_empty.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/is_empty.py", line 7, in <module>
    res = fluid.layers.is_empty(x=input)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/control_flow.py", line 1826, in is_empty
    type='is_empty', inputs={'X': [x]}, outputs={'Out': [cond]})
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1663, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1025, in __init__
    in_arg_names.append(cpt.to_text(arg.name))
AttributeError: 'builtin_function_or_method' object has no attribute 'name'


FileName:sigmoid_cross_entropy_with_logits.py:
---------------------------

successful


FileName:sequence_conv_pool.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sequence_conv_pool.py", line 7, in <module>
    input_dim = len(word_dict)
NameError: name 'word_dict' is not defined


FileName:sequence_reshape.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sequence_reshape.py", line 7, in <module>
    x = fluid.layers.data(shape=[5, 20], dtype='float32', lod_level=1)
TypeError: data() takes at least 2 arguments (3 given)


FileName:ErrorClipByValue.py:
---------------------------

  File "./api_codes/ErrorClipByValue.py", line 7
    var = fluid.framework.Variable(..., error_clip=ErrorClipByValue(max=5.0), ...)
                                   ^
SyntaxError: invalid syntax


FileName:pool2d.py:
---------------------------

successful


FileName:DistributeTranspiler(1).py:
---------------------------

  File "./api_codes/DistributeTranspiler(1).py", line 32
    num_trainers=len(trainers.split(",)),
                                        ^
SyntaxError: EOL while scanning string literal


FileName:smooth_l1.py:
---------------------------

successful


FileName:dynamic_lstmp.py:
---------------------------

successful


FileName:ssd_loss.py:
---------------------------

successful


FileName:sampling_id.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sampling_id.py", line 7, in <module>
    x = layers.data(
NameError: name 'layers' is not defined


FileName:natural_exp_decay.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/natural_exp_decay.py", line 7, in <module>
    if not staircase:
NameError: name 'staircase' is not defined


FileName:Print.py:
---------------------------

  File "./api_codes/Print.py", line 7
    value = some_layer(...)
                       ^
SyntaxError: invalid syntax


FileName:Program. clone.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Program. clone.py", line 9, in <module>
    optimizer.minimize()
TypeError: minimize() takes at least 2 arguments (1 given)


FileName:resize_bilinear.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/resize_bilinear.py", line 7, in <module>
    out = fluid.layers.resize_bilinear(input, out_shape=[12, 12])
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 7351, in resize_bilinear
    align_corners, align_mode)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 7208, in image_resize
    dtype = helper.input_dtype()
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 95, in input_dtype
    dtype = each.dtype
AttributeError: 'NoneType' object has no attribute 'dtype'


FileName:reverse.py:
---------------------------

  File "./api_codes/reverse.py", line 7
    out = fluid.layers.reverse(x=in, axis=0)
                                  ^
SyntaxError: invalid syntax


FileName:fill_constant_batch_size_like.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/fill_constant_batch_size_like.py", line 8, in <module>
    input=like, shape=[1], value=0, dtype='int64')
NameError: name 'like' is not defined


FileName:ChunkEvaluator.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/ChunkEvaluator.py", line 8, in <module>
    data = fluid.layers.data(name="data", shape=[32, 32], dtype="int32")
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 100, in data
    is_data=True)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py", line 353, in create_global_variable
    *args, persistable=persistable, **kwargs)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1527, in create_var
    var = Variable(block=self, *args, **kwargs)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 440, in __init__
    "matched.".format(self.name, old_shape, shape))
ValueError: Variable data has been created before. the previous shape is (-1L, 1L); the new shape is (-1, 32, 32). They are not matched.


FileName:generate_mask_labels.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/generate_mask_labels.py", line 14, in <module>
    for semgs in batch_semgs:
NameError: name 'batch_semgs' is not defined


FileName:clip_by_norm.py:
---------------------------

successful


FileName:ParallelExecutor. run.py:
---------------------------

  File "./api_codes/ParallelExecutor. run.py", line 11
    fetch_list=[avg_cost.name]))
                               ^
SyntaxError: invalid syntax


FileName:DataFeedDesc. set_dense_slots.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DataFeedDesc. set_dense_slots.py", line 7, in <module>
    data_feed = fluid.DataFeedDesc('data.proto')
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/data_feed_desc.py", line 72, in __init__
    with open(proto_file, 'r') as f:
IOError: [Errno 2] No such file or directory: 'data.proto'


FileName:elementwise_max.py:
---------------------------

  File "./api_codes/elementwise_max.py", line 7
    shape(X) = (2, 3, 4, 5), shape(Y) = (,)
                                         ^
SyntaxError: invalid syntax


FileName:Program.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Program.py", line 12, in <module>
    fluid.layers.fc(name="fc", shape=[10], dtype='float32', act="relu")
TypeError: fc() got an unexpected keyword argument 'shape'


FileName:L2DecayRegularizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/L2DecayRegularizer.py", line 11, in <module>
    optimizer.minimize(avg_cost)
NameError: name 'avg_cost' is not defined


FileName:huber_loss_2.py:
---------------------------

  File "./api_codes/huber_loss_2.py", line 7
    huber\_loss = 0.5 * (label - input) * (label - input)
                                                        ^
SyntaxError: unexpected character after line continuation character


FileName:reduce_max.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/reduce_max.py", line 11, in <module>
    fluid.layers.reduce_max(x)  # [0.9]
NameError: name 'x' is not defined


FileName:WeightNormParamAttr.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/WeightNormParamAttr.py", line 10, in <module>
    param_attr=WeightNormParamAttr(
NameError: name 'WeightNormParamAttr' is not defined


FileName:create_py_reader_by_data.py:
---------------------------

  File "./api_codes/create_py_reader_by_data.py", line 10
    img, label = fluid.layers.read_file(reader)
      ^
SyntaxError: invalid syntax


FileName:lrn.py:
---------------------------

successful


FileName:huber_loss.py:
---------------------------

  File "./api_codes/huber_loss.py", line 8
    loss = fluid.layers.huber_loss(input=predictions, label=label, 1.0)
SyntaxError: non-keyword arg after keyword arg


FileName:box_clip.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/box_clip.py", line 11, in <module>
    input=boxes, im_info=im_info, inplace=True)
TypeError: box_clip() got an unexpected keyword argument 'inplace'


FileName:load.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/load.py", line 3, in <module>
    fluid.layers.load(tmp_tensor, "./tmp_tensor.bin")
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 1216, in load
    helper.append_op(type="load", inputs={}, output={"Out": out}, args=attrs)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1663, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1067, in __init__
    self.desc.check_attrs()
paddle.fluid.core.EnforceNotMet: Attribute 'file_path' is required! at [/home/users/dongdaxiang/github_develop/Paddle/paddle/fluid/framework/attribute.h:276]
PaddlePaddle Call Stacks: 
0       0x7f17291b4510p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f17291b4889p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f17293c7cdep std::_Function_handler<void (std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >*), paddle::framework::TypedAttrChecker<std::string> >::_M_invoke(std::_Any_data const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >*) + 542
3       0x7f172930ec20p paddle::framework::OpDesc::CheckAttrs() + 304
4       0x7f17292672efp
5       0x7f17291e7804p
6       0x7f1826c55bb8p PyEval_EvalFrameEx + 25016
7       0x7f1826c590bdp PyEval_EvalCodeEx + 2061
8       0x7f1826bcff85p
9       0x7f1826b9ddf3p PyObject_Call + 67
10      0x7f1826bac9cdp
11      0x7f1826b9ddf3p PyObject_Call + 67
12      0x7f1826c0bbafp
13      0x7f1826c0846fp
14      0x7f1826b9ddf3p PyObject_Call + 67
15      0x7f1826c534a6p PyEval_EvalFrameEx + 15014
16      0x7f1826c590bdp PyEval_EvalCodeEx + 2061
17      0x7f1826bcff85p
18      0x7f1826b9ddf3p PyObject_Call + 67
19      0x7f1826c52f97p PyEval_EvalFrameEx + 13719
20      0x7f1826c590bdp PyEval_EvalCodeEx + 2061
21      0x7f1826c56345p PyEval_EvalFrameEx + 26949
22      0x7f1826c590bdp PyEval_EvalCodeEx + 2061
23      0x7f1826c56345p PyEval_EvalFrameEx + 26949
24      0x7f1826c590bdp PyEval_EvalCodeEx + 2061
25      0x7f1826c591f2p PyEval_EvalCode + 50
26      0x7f1826c81f42p PyRun_FileExFlags + 146
27      0x7f1826c832d9p PyRun_SimpleFileExFlags + 217
28      0x7f1826c9900dp Py_Main + 3149
29      0x7f1825e96bd5p __libc_start_main + 245
30            0x4007a1p



FileName:beam_search.py:
---------------------------

  File "./api_codes/beam_search.py", line 13
    y=layers.reshape(
    ^
IndentationError: unexpected indent


FileName:flatten.py:
---------------------------

successful


FileName:save_params.py:
---------------------------

successful


FileName:array_write.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/array_write.py", line 9, in <module>
    arr = layers.array_write(tmp, i=i)
NameError: name 'layers' is not defined


FileName:dropout.py:
---------------------------

successful


FileName:program_guard.py:
---------------------------

  File "./api_codes/program_guard.py", line 5
    data = fluid.layers.data(...)
                             ^
SyntaxError: invalid syntax


FileName:sequence_softmax.py:
---------------------------

successful


FileName:fc.py:
---------------------------

successful


FileName:row_conv.py:
---------------------------

successful


FileName:cast.py:
---------------------------

successful


FileName:py_reader.py:
---------------------------

  File "./api_codes/py_reader.py", line 10
    img, label = fluid.layers.read_file(reader)
      ^
SyntaxError: invalid syntax


FileName:autoincreased_step_counter.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/autoincreased_step_counter.py", line 8, in <module>
    counter_name='@LR_DECAY_COUNTER@', begin=begin, step=1)
NameError: name 'begin' is not defined


FileName:logical_xor.py:
---------------------------

successful


FileName:softmax.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/softmax.py", line 7, in <module>
    fc = fluid.layers.fc(input=x, size=10)
NameError: name 'x' is not defined


FileName:relu6.py:
---------------------------

successful


FileName:profiler.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/profiler.py", line 10, in <module>
    for pass_id in range(pass_num):
NameError: name 'pass_num' is not defined


FileName:ParallelExecutor. run_2.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/ParallelExecutor. run_2.py", line 7, in <module>
    exe = ParallelExecutor()
NameError: name 'ParallelExecutor' is not defined


FileName:DetectionMAP.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DetectionMAP.py", line 7, in <module>
    exe = fluid.Executor(place)
NameError: name 'place' is not defined


FileName:XavierInitializer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/XavierInitializer.py", line 8, in <module>
    input=queries, size=10,
NameError: name 'queries' is not defined


FileName:create_tensor.py:
---------------------------

successful


FileName:save_persistables.py:
---------------------------

successful


FileName:reshape.py:
---------------------------

successful


FileName:Executor. run_1(1).py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Executor. run_1(1).py", line 7, in <module>
    cpu = core.CPUPlace()
NameError: name 'core' is not defined


FileName:DynamicRNN.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DynamicRNN.py", line 2, in <module>
    data = fluid.layers.data(name='sentence', dtype='int64', lod_level=1)
TypeError: data() takes at least 2 arguments (3 given)


FileName:sum.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sum.py", line 7, in <module>
    input = layers.data(name="input", shape=[13, 11], dtype='float32')
NameError: name 'layers' is not defined


FileName:elementwise_sub.py:
---------------------------

  File "./api_codes/elementwise_sub.py", line 7
    shape(X) = (2, 3, 4, 5), shape(Y) = (,)
                                         ^
SyntaxError: invalid syntax


FileName:Switch.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Switch.py", line 13, in <module>
    one_var = tensor.fill_constant(
NameError: name 'tensor' is not defined


FileName:data_norm.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/data_norm.py", line 7, in <module>
    data = fluid.layers.data(input=x, size=200, param_attr='fc1.w')
NameError: name 'x' is not defined


FileName:CompositeMetric.py:
---------------------------

  File "./api_codes/CompositeMetric.py", line 15
    for pass in range(PASSES):
           ^
SyntaxError: invalid syntax


FileName:concat.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/concat.py", line 7, in <module>
    out = fluid.layers.concat(input=[Efirst, Esecond, Ethird, Efourth])
NameError: name 'Efirst' is not defined


FileName:py_func.py:
---------------------------

successful


FileName:logical_not.py:
---------------------------

successful


FileName:py_reader_1.py:
---------------------------

  File "./api_codes/py_reader_1.py", line 16
    test_reader = fluid.layers.py_reader(capacity=32,
              ^
SyntaxError: invalid syntax


FileName:create_global_var.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/create_global_var.py", line 7, in <module>
    var = fluid.create_global_var(shape=[2,3], value=1.0, dtype='float32',
AttributeError: 'module' object has no attribute 'create_global_var'


FileName:DecayedAdagradOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DecayedAdagradOptimizer.py", line 8, in <module>
    optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:hash.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/hash.py", line 7, in <module>
    word_dict = paddle.dataset.imdb.word_dict()
NameError: name 'paddle' is not defined


FileName:auc(1).py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/auc(1).py", line 8, in <module>
    prediction = network(image, is_infer=True)
NameError: name 'network' is not defined


FileName:append_backward.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/append_backward.py", line 9, in <module>
    avg_loss = fluid.layers.mean(loss)
NameError: name 'loss' is not defined


FileName:split.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/split.py", line 8, in <module>
    x0, x1, x2 = fluid.layers.split(x, num_or_sections=3, dim=1)
NameError: name 'x' is not defined


FileName:fill_constant.py:
---------------------------

successful


FileName:MSRAInitializer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/MSRAInitializer.py", line 8, in <module>
    input=queries, size=10,
NameError: name 'queries' is not defined


FileName:ModelAverage.py:
---------------------------

  File "./api_codes/ModelAverage.py", line 14
    exe.run(fluid.default_main_program()...)
                                         ^
SyntaxError: invalid syntax


FileName:Accuracy.py:
---------------------------

  File "./api_codes/Accuracy.py", line 12
    for pass in range(PASSES):
           ^
SyntaxError: invalid syntax


FileName:AdamaxOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/AdamaxOptimizer.py", line 8, in <module>
    optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:MomentumOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/MomentumOptimizer.py", line 8, in <module>
    optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:Program. clone_1.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Program. clone_1.py", line 16, in <module>
    sgd.minimize(loss)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 487, in minimize
    no_grad_set=no_grad_set)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 392, in backward
    no_grad_set, callbacks)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/backward.py", line 525, in append_backward
    _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/backward.py", line 361, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected dy_dims.size() == rank, but received dy_dims.size():1 != rank:2.
Input(Y@Grad) and Input(X) should have the same rank. at [/home/users/dongdaxiang/github_develop/Paddle/paddle/fluid/operators/cross_entropy_op.cc:98]
PaddlePaddle Call Stacks: 
0       0x7f48ba7fda38p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f48ba7fdd87p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f48bb0af9dbp paddle::operators::CrossEntropyGradientOpBase::InferShape(paddle::framework::InferShapeContext*) const + 4619
3       0x7f48bb0b039dp paddle::operators::CrossEntropyGradientOp2::InferShape(paddle::framework::InferShapeContext*) const + 109
4       0x7f48ba95948ep paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 862
5       0x7f48ba8aedfcp
6       0x7f48ba830804p
7       0x7f49b829ebb8p PyEval_EvalFrameEx + 25016
8       0x7f49b82a20bdp PyEval_EvalCodeEx + 2061
9       0x7f49b829f345p PyEval_EvalFrameEx + 26949
10      0x7f49b82a20bdp PyEval_EvalCodeEx + 2061
11      0x7f49b829f345p PyEval_EvalFrameEx + 26949
12      0x7f49b82a20bdp PyEval_EvalCodeEx + 2061
13      0x7f49b829f345p PyEval_EvalFrameEx + 26949
14      0x7f49b82a20bdp PyEval_EvalCodeEx + 2061
15      0x7f49b829f345p PyEval_EvalFrameEx + 26949
16      0x7f49b82a20bdp PyEval_EvalCodeEx + 2061
17      0x7f49b82a21f2p PyEval_EvalCode + 50
18      0x7f49b82caf42p PyRun_FileExFlags + 146
19      0x7f49b82cc2d9p PyRun_SimpleFileExFlags + 217
20      0x7f49b82e200dp Py_Main + 3149
21      0x7f49b74dfbd5p __libc_start_main + 245
22            0x4007a1p



FileName:anchor_generator.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/anchor_generator.py", line 7, in <module>
    anchor, var = anchor_generator(
NameError: name 'anchor_generator' is not defined


FileName:glu.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/glu.py", line 8, in <module>
    output = fluid.nets.glu(input=data, dim=1)  # shape of output: [3, 3, 9]
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/nets.py", line 334, in glu
    a, b = layers.split(input, num_or_sections=2, dim=dim)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 4797, in split
    'axis': dim
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1663, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1070, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected in_axis_dim % num == 0, but received in_axis_dim % num:1 != 0:0.
tensor split does not result in an equal division at [/home/users/dongdaxiang/github_develop/Paddle/paddle/fluid/operators/split_op.cc:44]
PaddlePaddle Call Stacks: 
0       0x7efc44c5ca38p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7efc44c5cd87p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7efc44f546e3p paddle::operators::SplitOp::InferShape(paddle::framework::InferShapeContext*) const + 3075
3       0x7efc44db848ep paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 862
4       0x7efc44d0ddfcp
5       0x7efc44c8f804p
6       0x7efd426fdbb8p PyEval_EvalFrameEx + 25016
7       0x7efd427010bdp PyEval_EvalCodeEx + 2061
8       0x7efd42677f85p
9       0x7efd42645df3p PyObject_Call + 67
10      0x7efd426549cdp
11      0x7efd42645df3p PyObject_Call + 67
12      0x7efd426b3bafp
13      0x7efd426b046fp
14      0x7efd42645df3p PyObject_Call + 67
15      0x7efd426fb4a6p PyEval_EvalFrameEx + 15014
16      0x7efd427010bdp PyEval_EvalCodeEx + 2061
17      0x7efd42677f85p
18      0x7efd42645df3p PyObject_Call + 67
19      0x7efd426faf97p PyEval_EvalFrameEx + 13719
20      0x7efd427010bdp PyEval_EvalCodeEx + 2061
21      0x7efd426fe345p PyEval_EvalFrameEx + 26949
22      0x7efd427010bdp PyEval_EvalCodeEx + 2061
23      0x7efd426fe345p PyEval_EvalFrameEx + 26949
24      0x7efd427010bdp PyEval_EvalCodeEx + 2061
25      0x7efd426fe345p PyEval_EvalFrameEx + 26949
26      0x7efd427010bdp PyEval_EvalCodeEx + 2061
27      0x7efd427011f2p PyEval_EvalCode + 50
28      0x7efd42729f42p PyRun_FileExFlags + 146
29      0x7efd4272b2d9p PyRun_SimpleFileExFlags + 217
30      0x7efd4274100dp Py_Main + 3149
31      0x7efd4193ebd5p __libc_start_main + 245
32            0x4007a1p



FileName:piecewise_decay.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/piecewise_decay.py", line 9, in <module>
    if step < 10000:
NameError: name 'step' is not defined


FileName:sequence_expand_as.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sequence_expand_as.py", line 10, in <module>
    out = layers.sequence_expand_as(x=x, y=y)
NameError: name 'layers' is not defined


FileName:soft_relu.py:
---------------------------

successful


FileName:margin_rank_loss.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/margin_rank_loss.py", line 10, in <module>
    out = fluid.layers.margin_rank_loss(label, left, right)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 8175, in margin_rank_loss
    attrs={'margin': margin})
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1663, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1070, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: All inputs must be 2-D tensor with shape [batch_size x 1]. at [/home/users/dongdaxiang/github_develop/Paddle/paddle/fluid/operators/margin_rank_loss_op.cc:37]
PaddlePaddle Call Stacks: 
0       0x7f899fec7510p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f899fec7889p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f89a0335f33p paddle::operators::MarginRankLossOp::InferShape(paddle::framework::InferShapeContext*) const + 819
3       0x7f89a002348ep paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 862
4       0x7f899ff78dfcp
5       0x7f899fefa804p
6       0x7f8a9d968bb8p PyEval_EvalFrameEx + 25016
7       0x7f8a9d96c0bdp PyEval_EvalCodeEx + 2061
8       0x7f8a9d8e2f85p
9       0x7f8a9d8b0df3p PyObject_Call + 67
10      0x7f8a9d8bf9cdp
11      0x7f8a9d8b0df3p PyObject_Call + 67
12      0x7f8a9d91ebafp
13      0x7f8a9d91b46fp
14      0x7f8a9d8b0df3p PyObject_Call + 67
15      0x7f8a9d9664a6p PyEval_EvalFrameEx + 15014
16      0x7f8a9d96c0bdp PyEval_EvalCodeEx + 2061
17      0x7f8a9d8e2f85p
18      0x7f8a9d8b0df3p PyObject_Call + 67
19      0x7f8a9d965f97p PyEval_EvalFrameEx + 13719
20      0x7f8a9d96c0bdp PyEval_EvalCodeEx + 2061
21      0x7f8a9d969345p PyEval_EvalFrameEx + 26949
22      0x7f8a9d96c0bdp PyEval_EvalCodeEx + 2061
23      0x7f8a9d969345p PyEval_EvalFrameEx + 26949
24      0x7f8a9d96c0bdp PyEval_EvalCodeEx + 2061
25      0x7f8a9d96c1f2p PyEval_EvalCode + 50
26      0x7f8a9d994f42p PyRun_FileExFlags + 146
27      0x7f8a9d9962d9p PyRun_SimpleFileExFlags + 217
28      0x7f8a9d9ac00dp Py_Main + 3149
29      0x7f8a9cba9bd5p __libc_start_main + 245
30            0x4007a1p



FileName:brelu.py:
---------------------------

successful


FileName:tree_conv.py:
---------------------------

  File "./api_codes/tree_conv.py", line 7
    nodes_vector = layers.data(name='vectors', shape=[None, 10, 5], dtype='float32)
                                                                                  ^
SyntaxError: EOL while scanning string literal


FileName:label_smooth.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/label_smooth.py", line 7, in <module>
    label = layers.data(name="label", shape=[1], dtype="float32")
NameError: name 'layers' is not defined


FileName:softmax_with_cross_entropy.py:
---------------------------

successful


FileName:chunk_eval_4.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/chunk_eval_4.py", line 8, in <module>
    input=hidden, label=label, param_attr=ParamAttr(name="crfw"))
NameError: name 'hidden' is not defined


FileName:pad_constant_like.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/pad_constant_like.py", line 9, in <module>
    out = fluid.layers.pad_constant_like(x=x, y=y, pad_value=0.)
NameError: name 'x' is not defined


FileName:Precision.py:
---------------------------

  File "./api_codes/Precision.py", line 8
    for pass in range(PASSES):
           ^
SyntaxError: invalid syntax


FileName:matmul.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/matmul.py", line 9, in <module>
    fluid.layers.matmul(x, y)  # out: [B, ..., M, N]
NameError: name 'x' is not defined


FileName:save_vars.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/save_vars.py", line 16, in <module>
    fluid.io.save_vars(executor=exe, dirname=path, main_program=prog,
NameError: name 'path' is not defined


FileName:detection_output.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/detection_output.py", line 7, in <module>
    pb = layers.data(name='prior_box', shape=[10, 4],
NameError: name 'layers' is not defined


FileName:Program. clone_2.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Program. clone_2.py", line 20, in <module>
    sgd.minimize(loss)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 487, in minimize
    no_grad_set=no_grad_set)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 392, in backward
    no_grad_set, callbacks)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/backward.py", line 525, in append_backward
    _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/backward.py", line 361, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected dy_dims.size() == rank, but received dy_dims.size():1 != rank:2.
Input(Y@Grad) and Input(X) should have the same rank. at [/home/users/dongdaxiang/github_develop/Paddle/paddle/fluid/operators/cross_entropy_op.cc:98]
PaddlePaddle Call Stacks: 
0       0x7f4fee3baa38p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f4fee3bad87p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f4feec6c9dbp paddle::operators::CrossEntropyGradientOpBase::InferShape(paddle::framework::InferShapeContext*) const + 4619
3       0x7f4feec6d39dp paddle::operators::CrossEntropyGradientOp2::InferShape(paddle::framework::InferShapeContext*) const + 109
4       0x7f4fee51648ep paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 862
5       0x7f4fee46bdfcp
6       0x7f4fee3ed804p
7       0x7f50ebe5bbb8p PyEval_EvalFrameEx + 25016
8       0x7f50ebe5f0bdp PyEval_EvalCodeEx + 2061
9       0x7f50ebe5c345p PyEval_EvalFrameEx + 26949
10      0x7f50ebe5f0bdp PyEval_EvalCodeEx + 2061
11      0x7f50ebe5c345p PyEval_EvalFrameEx + 26949
12      0x7f50ebe5f0bdp PyEval_EvalCodeEx + 2061
13      0x7f50ebe5c345p PyEval_EvalFrameEx + 26949
14      0x7f50ebe5f0bdp PyEval_EvalCodeEx + 2061
15      0x7f50ebe5c345p PyEval_EvalFrameEx + 26949
16      0x7f50ebe5f0bdp PyEval_EvalCodeEx + 2061
17      0x7f50ebe5f1f2p PyEval_EvalCode + 50
18      0x7f50ebe87f42p PyRun_FileExFlags + 146
19      0x7f50ebe892d9p PyRun_SimpleFileExFlags + 217
20      0x7f50ebe9f00dp Py_Main + 3149
21      0x7f50eb09cbd5p __libc_start_main + 245
22            0x4007a1p



FileName:sums.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sums.py", line 9, in <module>
    a0 = layers.array_read(array=tmp, i=i)
NameError: name 'layers' is not defined


FileName:GradientClipByGlobalNorm.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/GradientClipByGlobalNorm.py", line 7, in <module>
    p_g_clip = fluid.backward.append_backward(loss=avg_cost_clip)
NameError: name 'avg_cost_clip' is not defined


FileName:transpose.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/transpose.py", line 11, in <module>
    x_transposed = layers.transpose(x, perm=[1, 0, 2])
NameError: name 'layers' is not defined


FileName:gru_unit.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/gru_unit.py", line 8, in <module>
    x_t = fluid.layers.fc(input=x_t_data, size=30)
NameError: name 'x_t_data' is not defined


FileName:leaky_relu.py:
---------------------------

successful


FileName:Executor. run.py:
---------------------------

  File "./api_codes/Executor. run.py", line 13
    >>> adam.minimize(loss)
    ^
IndentationError: unexpected indent


FileName:pad2d.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/pad2d.py", line 8, in <module>
    result = fluid.layers.pad2d(input=data, padding=[1,2,3,4], mode='reflect')
TypeError: pad2d() got an unexpected keyword argument 'padding'


FileName:adaptive_pool2d.py:
---------------------------

successful


FileName:force_init_on_cpu.py:
---------------------------

  File "./api_codes/force_init_on_cpu.py", line 8
    create_op('force_cpu': force_init_on_cpu())
                         ^
SyntaxError: invalid syntax


FileName:beam_search_decode.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/beam_search_decode.py", line 9, in <module>
    finished_ids, finished_scores = layers.beam_search_decode(
NameError: name 'layers' is not defined


FileName:load_vars.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/load_vars.py", line 16, in <module>
    fluid.io.load_vars(executor=exe, dirname=path, main_program=prog,
NameError: name 'path' is not defined


FileName:array_read.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/array_read.py", line 9, in <module>
    arr = layers.array_read(tmp, i=i)
NameError: name 'layers' is not defined


FileName:add_position_encoding.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/add_position_encoding.py", line 7, in <module>
    position_tensor = fluid.layers.add_position_encoding(input=tensor)
NameError: name 'tensor' is not defined


FileName:thresholded_relu.py:
---------------------------

successful


FileName:IfElse.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/IfElse.py", line 8, in <module>
    input=label, dtype='int64', shape=[1], value=5.0)
NameError: name 'label' is not defined


FileName:scatter.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/scatter.py", line 7, in <module>
    output = fluid.layers.scatter(input, index, updates)
NameError: name 'index' is not defined


FileName:name_scope.py:
---------------------------

  File "./api_codes/name_scope.py", line 8
    ...
    ^
SyntaxError: invalid syntax


FileName:crop.py:
---------------------------

successful


FileName:square_error_cost.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/square_error_cost.py", line 7, in <module>
    y = layers.data(name='y', shape=[1], dtype='float32')
NameError: name 'layers' is not defined


FileName:save_inference_model.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/save_inference_model.py", line 10, in <module>
    target_vars=[predict_var], executor=exe)
NameError: name 'predict_var' is not defined


FileName:grid_sampler.py:
---------------------------

  File "./api_codes/grid_sampler.py", line 9
    grid = fluid.layers.affine_grid(input=theta, size=[3, 10, 32, 32]})
                                                                     ^
SyntaxError: invalid syntax


FileName:TruncatedNormalInitializer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/TruncatedNormalInitializer.py", line 7, in <module>
    fc = fluid.layers.fc(input=x, size=10,
NameError: name 'x' is not defined


FileName:start_profiler.py:
---------------------------


------------------------->     Profiling Report     <-------------------------

Place: CUDA
Time unit: ms
Sorted by total time in descending order in the same thread

EventCalls       Total       Min.        Max.        Ave.        Ratio.      

successful


FileName:reduce_prod.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/reduce_prod.py", line 11, in <module>
    fluid.layers.reduce_prod(x)  # [0.0002268]
NameError: name 'x' is not defined


FileName:elementwise_pow.py:
---------------------------

  File "./api_codes/elementwise_pow.py", line 7
    shape(X) = (2, 3, 4, 5), shape(Y) = (,)
                                         ^
SyntaxError: invalid syntax


FileName:Auc.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Auc.py", line 7, in <module>
    pred = fluid.layers.fc(input=data, size=1000, act="tanh")
NameError: name 'data' is not defined


FileName:WeightedAverage.py:
---------------------------

successful
/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/average.py:64: Warning: The WeightedAverage is deprecated, please use fluid.metrics.Accuracy instead.
  (self.__class__.__name__), Warning)


FileName:data.py:
---------------------------

successful


FileName:EditDistance.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/EditDistance.py", line 7, in <module>
    distances, seq_num = fluid.layers.edit_distance(input, label)
NameError: name 'label' is not defined


FileName:load_inference_model.py:
---------------------------

  File "./api_codes/load_inference_model.py", line 10
    [inference_program, feed_target_names, fetch_targets] =
                                                          ^
SyntaxError: invalid syntax


FileName:sequence_unpad.py:
---------------------------

successful


FileName:random_crop.py:
---------------------------

successful


FileName:BilinearInitializer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/BilinearInitializer.py", line 8, in <module>
    w_attr = ParamAttr(learning_rate=0., regularizer=L2Decay(0.),
NameError: name 'ParamAttr' is not defined


FileName:dynamic_gru.py:
---------------------------

successful


FileName:simple_img_conv_pool.py:
---------------------------

successful


FileName:chunk_eval.py:
---------------------------

  File "./api_codes/chunk_eval.py", line 7
    ====== ====== ======  =====  ==  ============   =====  ===== =====  ==  =========
     ^
SyntaxError: invalid syntax


FileName:multiclass_nms.py:
---------------------------

successful


FileName:l2_normalize.py:
---------------------------

successful


FileName:rpn_target_assign.py:
---------------------------

  File "./api_codes/rpn_target_assign.py", line 15
    loc_pred, score_pred, loc_target, score_target, bbox_inside_weight =
                                                                       ^
SyntaxError: invalid syntax


FileName:Executor. run_2(1).py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Executor. run_2(1).py", line 7, in <module>
    x = numpy.random.random(size=(10, 1)).astype('float32')
NameError: name 'numpy' is not defined


FileName:array_length.py:
---------------------------

successful


FileName:reduce_min.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/reduce_min.py", line 11, in <module>
    fluid.layers.reduce_min(x)  # [0.1]
NameError: name 'x' is not defined


FileName:sequence_concat.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sequence_concat.py", line 7, in <module>
    out = fluid.layers.sequence_concat(input=[seq1, seq2, seq3])
NameError: name 'seq1' is not defined


FileName:conv2d.py:
---------------------------

successful


FileName:scope_guard(1).py:
---------------------------

  File "./api_codes/scope_guard(1).py", line 4
    ...
    ^
SyntaxError: invalid syntax


FileName:AsyncExecutor.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/AsyncExecutor.py", line 7, in <module>
    data_feed = fluid.DataFeedDesc('data.proto')
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/data_feed_desc.py", line 72, in __init__
    with open(proto_file, 'r') as f:
IOError: [Errno 2] No such file or directory: 'data.proto'


FileName:gaussian_random.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/gaussian_random.py", line 7, in <module>
    out = layers.gaussian_random(shape=[20, 30])
NameError: name 'layers' is not defined


FileName:adaptive_pool3d.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/adaptive_pool3d.py", line 30, in <module>
    pool_type='avg')
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 2925, in adaptive_pool3d
    "adaptive": True,
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1663, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1070, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Input size and pooling size should be consistent. at [/home/users/dongdaxiang/github_develop/Paddle/paddle/fluid/operators/pool_op.cc:70]
PaddlePaddle Call Stacks: 
0       0x7f5688945510p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f5688945889p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f56895c597ep paddle::operators::PoolOp::InferShape(paddle::framework::InferShapeContext*) const + 3598
3       0x7f5688aa148ep paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 862
4       0x7f56889f6dfcp
5       0x7f5688978804p
6       0x7f57863e6bb8p PyEval_EvalFrameEx + 25016
7       0x7f57863ea0bdp PyEval_EvalCodeEx + 2061
8       0x7f5786360f85p
9       0x7f578632edf3p PyObject_Call + 67
10      0x7f578633d9cdp
11      0x7f578632edf3p PyObject_Call + 67
12      0x7f578639cbafp
13      0x7f578639946fp
14      0x7f578632edf3p PyObject_Call + 67
15      0x7f57863e44a6p PyEval_EvalFrameEx + 15014
16      0x7f57863ea0bdp PyEval_EvalCodeEx + 2061
17      0x7f5786360f85p
18      0x7f578632edf3p PyObject_Call + 67
19      0x7f57863e3f97p PyEval_EvalFrameEx + 13719
20      0x7f57863ea0bdp PyEval_EvalCodeEx + 2061
21      0x7f57863e7345p PyEval_EvalFrameEx + 26949
22      0x7f57863ea0bdp PyEval_EvalCodeEx + 2061
23      0x7f57863e7345p PyEval_EvalFrameEx + 26949
24      0x7f57863ea0bdp PyEval_EvalCodeEx + 2061
25      0x7f57863ea1f2p PyEval_EvalCode + 50
26      0x7f5786412f42p PyRun_FileExFlags + 146
27      0x7f57864142d9p PyRun_SimpleFileExFlags + 217
28      0x7f578642a00dp Py_Main + 3149
29      0x7f5785627bd5p __libc_start_main + 245
30            0x4007a1p



FileName:init_on_cpu.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/init_on_cpu.py", line 7, in <module>
    with init_on_cpu():
NameError: name 'init_on_cpu' is not defined


FileName:log.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/log.py", line 7, in <module>
    output = fluid.layers.log(x)
NameError: name 'x' is not defined


FileName:uniform_random.py:
---------------------------

successful


FileName:topk.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/topk.py", line 7, in <module>
    top5_values, top5_indices = layers.topk(input, k=5)
NameError: name 'layers' is not defined


FileName:DataFeeder_2(1).py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DataFeeder_2(1).py", line 10, in <module>
    main_program.global_block().var(var_name) for var_name in feed_vars_name
NameError: name 'feed_vars_name' is not defined


FileName:FtrlOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/FtrlOptimizer.py", line 8, in <module>
    _, params_grads = optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:DataFeedDesc.py:
---------------------------

  File "./api_codes/DataFeedDesc.py", line 7
    name: "MultiSlotDataFeed"
        ^
SyntaxError: invalid syntax


FileName:similarity_focus.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/similarity_focus.py", line 9, in <module>
    x = fluid.layers.layer_norm(input=data, axis=1, indexes=[0])
TypeError: layer_norm() got an unexpected keyword argument 'axis'


FileName:mean_iou.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/mean_iou.py", line 7, in <module>
    iou, wrongs, corrects = fluid.layers.mean_iou(predict, label, num_classes)
NameError: name 'predict' is not defined


FileName:assign.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/assign.py", line 8, in <module>
    hidden = fluid.layers.fc(input=data, size=10)
NameError: name 'data' is not defined


FileName:exponential_decay.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/exponential_decay.py", line 14, in <module>
    sgd_optimizer.minimize(avg_cost)
NameError: name 'avg_cost' is not defined


FileName:elu.py:
---------------------------

successful


FileName:img_conv_group.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/img_conv_group.py", line 15, in <module>
    pool_stride=2)
TypeError: img_conv_group() got an unexpected keyword argument 'num_channels'


FileName:ParallelExecutor.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/ParallelExecutor.py", line 7, in <module>
    train_exe = fluid.ParallelExecutor(use_cuda=True, loss_name=loss.name)
NameError: name 'loss' is not defined


FileName:shuffle_channel.py:
---------------------------

successful


FileName:roi_perspective_transform.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/roi_perspective_transform.py", line 7, in <module>
    out = fluid.layers.roi_perspective_transform(input, rois, 7, 7, 1.0)
NameError: name 'rois' is not defined


FileName:dynamic_lstm.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/dynamic_lstm.py", line 8, in <module>
    forward_proj = fluid.layers.fc(input=input_seq, size=hidden_dim * 4,
NameError: name 'input_seq' is not defined


FileName:gaussian_random_batch_size_like.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/gaussian_random_batch_size_like.py", line 7, in <module>
    input = layers.data(name="input", shape=[13, 11], dtype='float32')
NameError: name 'layers' is not defined


FileName:LarsMomentumOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/LarsMomentumOptimizer.py", line 8, in <module>
    optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:edit_distance.py:
---------------------------

successful


FileName:selu.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/selu.py", line 7, in <module>
    output = fluid.layers.selu(x)
NameError: name 'x' is not defined


FileName:multi_box_head.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/multi_box_head.py", line 8, in <module>
    inputs=[conv1, conv2, conv3, conv4, conv5, conv5],
NameError: name 'conv1' is not defined


FileName:affine_grid.py:
---------------------------

successful


FileName:uniform_random_batch_size_like.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/uniform_random_batch_size_like.py", line 7, in <module>
    input = layers.data(name="input", shape=[13, 11], dtype='float32')
NameError: name 'layers' is not defined


FileName:scaled_dot_product_attention.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/scaled_dot_product_attention.py", line 22, in <module>
    contexts = fluid.nets.scaled_dot_product_attention(queries, keys, values)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/nets.py", line 525, in scaled_dot_product_attention
    ctx_multiheads = layers.matmul(weights, v)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 4950, in matmul
    __check_input(x, y)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 4939, in __check_input
    (x_shape, y_shape))
ValueError: Invalid inputs for matmul. x: [3L, 6L, 5L], y: [3L, 6L, 10L]



FileName:L1DecayRegularizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/L1DecayRegularizer.py", line 11, in <module>
    optimizer.minimize(avg_cost)
NameError: name 'avg_cost' is not defined


FileName:reduce_sum.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/reduce_sum.py", line 11, in <module>
    fluid.layers.reduce_sum(x)  # [3.5]
NameError: name 'x' is not defined


FileName:Executor. close(1).py:
---------------------------

  File "./api_codes/Executor. close(1).py", line 9
    ...
    ^
SyntaxError: invalid syntax


FileName:reduce_mean.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/reduce_mean.py", line 11, in <module>
    fluid.layers.reduce_mean(x)  # [0.4375]
NameError: name 'x' is not defined


FileName:Preprocessor.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Preprocessor.py", line 7, in <module>
    preprocessor = fluid.layers.io.Preprocessor(reader=reader)
NameError: name 'reader' is not defined


FileName:chunk_eval_3.py:
---------------------------

  File "./api_codes/chunk_eval_3.py", line 7
    B-ORG  0
           ^
SyntaxError: invalid syntax


FileName:cuda_profiler.py:
---------------------------

W0409 20:20:57.224118  3858 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0409 20:20:57.227053  3858 device_context.cc:269] device: 0, cuDNN Version: 7.0.
W0409 20:20:57.227077  3858 device_context.cc:293] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.1, but CUDNN version in your machine is 7.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Traceback (most recent call last):
  File "./api_codes/cuda_profiler.py", line 16, in <module>
    input = np.random.random(dshape).astype('float32')
NameError: name 'np' is not defined


FileName:DataFeedDesc. set_use_slots.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DataFeedDesc. set_use_slots.py", line 7, in <module>
    data_feed = fluid.DataFeedDesc('data.proto')
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/data_feed_desc.py", line 72, in __init__
    with open(proto_file, 'r') as f:
IOError: [Errno 2] No such file or directory: 'data.proto'


FileName:DataFeeder_1.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DataFeeder_1.py", line 8, in <module>
    feeder = fluid.DataFeeder(place=place, feed_list=[data, label])
NameError: name 'data' is not defined


FileName:Recall.py:
---------------------------

  File "./api_codes/Recall.py", line 8
    for pass in range(PASSES):
           ^
SyntaxError: invalid syntax


FileName:space_to_depth.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/space_to_depth.py", line 10, in <module>
    x=data, blocksize=2)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 9790, in space_to_depth
    outputs={"Out": out})
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1663, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1070, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected x_dims.size() == 4, but received x_dims.size():5 != 4:4.
input should be a 4D tensor at [/home/users/dongdaxiang/github_develop/Paddle/paddle/fluid/operators/space_to_depth_op.cc:33]
PaddlePaddle Call Stacks: 
0       0x7fb96595ba38p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7fb96595bd87p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7fb9661bd844p paddle::operators::SpaceToDepthOp::InferShape(paddle::framework::InferShapeContext*) const + 4964
3       0x7fb965ab748ep paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 862
4       0x7fb965a0cdfcp
5       0x7fb96598e804p
6       0x7fba633fcbb8p PyEval_EvalFrameEx + 25016
7       0x7fba634000bdp PyEval_EvalCodeEx + 2061
8       0x7fba63376f85p
9       0x7fba63344df3p PyObject_Call + 67
10      0x7fba633539cdp
11      0x7fba63344df3p PyObject_Call + 67
12      0x7fba633b2bafp
13      0x7fba633af46fp
14      0x7fba63344df3p PyObject_Call + 67
15      0x7fba633fa4a6p PyEval_EvalFrameEx + 15014
16      0x7fba634000bdp PyEval_EvalCodeEx + 2061
17      0x7fba63376f85p
18      0x7fba63344df3p PyObject_Call + 67
19      0x7fba633f9f97p PyEval_EvalFrameEx + 13719
20      0x7fba634000bdp PyEval_EvalCodeEx + 2061
21      0x7fba633fd345p PyEval_EvalFrameEx + 26949
22      0x7fba634000bdp PyEval_EvalCodeEx + 2061
23      0x7fba633fd345p PyEval_EvalFrameEx + 26949
24      0x7fba634000bdp PyEval_EvalCodeEx + 2061
25      0x7fba634001f2p PyEval_EvalCode + 50
26      0x7fba63428f42p PyRun_FileExFlags + 146
27      0x7fba6342a2d9p PyRun_SimpleFileExFlags + 217
28      0x7fba6344000dp Py_Main + 3149
29      0x7fba6263dbd5p __libc_start_main + 245
30            0x4007a1p



FileName:AdagradOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/AdagradOptimizer.py", line 8, in <module>
    optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:reset_profiler.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/reset_profiler.py", line 8, in <module>
    with profiler.profiler(state, 'total', '/tmp/profile'):
NameError: name 'state' is not defined


FileName:psroi_pool.py:
---------------------------

  File "./api_codes/psroi_pool.py", line 7
    pool_out = fluid.layers.psroi_pool(input=x, rois=rois, 490, 1.0, 7, 7)
SyntaxError: non-keyword arg after keyword arg


FileName:equal.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/equal.py", line 7, in <module>
    less = fluid.layers.equal(x=label, y=limit)
NameError: name 'label' is not defined


FileName:DynamicRNN. memory.py:
---------------------------

successful


FileName:DataFeeder(1).py:
---------------------------

successful


FileName:UniformInitializer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/UniformInitializer.py", line 7, in <module>
    fc = fluid.layers.fc(input=x, size=10,
NameError: name 'x' is not defined


FileName:ParamAttr.py:
---------------------------

successful


FileName:load_persistables.py:
---------------------------

successful


FileName:Executor. close.py:
---------------------------

  File "./api_codes/Executor. close.py", line 9
    ...
    ^
SyntaxError: invalid syntax


FileName:BuildStrategy.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/BuildStrategy.py", line 11, in <module>
    loss_name=loss.name,
NameError: name 'loss' is not defined


FileName:NormalInitializer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/NormalInitializer.py", line 7, in <module>
    fc = fluid.layers.fc(input=x, size=10,
NameError: name 'x' is not defined


FileName:SGDOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/SGDOptimizer.py", line 8, in <module>
    sgd_optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:read_file.py:
---------------------------

  File "./api_codes/read_file.py", line 12
    data_file = fluid.layers.double_buffer(
    ^
IndentationError: unexpected indent


FileName:accuracy(1).py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/accuracy(1).py", line 8, in <module>
    label = fluid.layers.data(name="data", shape=[-1,1], dtype="int32")
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 100, in data
    is_data=True)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper_base.py", line 353, in create_global_variable
    *args, persistable=persistable, **kwargs)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1527, in create_var
    var = Variable(block=self, *args, **kwargs)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 440, in __init__
    "matched.".format(self.name, old_shape, shape))
ValueError: Variable data has been created before. the previous shape is (-1L, 32L, 32L); the new shape is (-1, 1). They are not matched.


FileName:DistributeTranspiler.py:
---------------------------

  File "./api_codes/DistributeTranspiler.py", line 32
    num_trainers=len(trainers.split(",)),
                                        ^
SyntaxError: EOL while scanning string literal


FileName:bpr_loss.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/bpr_loss.py", line 7, in <module>
    cost = fluid.layers.bpr_loss(input=predict, label=label)
NameError: name 'predict' is not defined


FileName:DynamicRNN. memory_1.py:
---------------------------

successful


FileName:sequence_last_step.py:
---------------------------

successful


FileName:bipartite_match.py:
---------------------------

successful


FileName:NumpyArrayInitializer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/NumpyArrayInitializer.py", line 7, in <module>
    fc = fluid.layers.fc(input=x, size=10,
NameError: name 'x' is not defined


FileName:sequence_slice.py:
---------------------------

successful


FileName:scope_guard.py:
---------------------------

  File "./api_codes/scope_guard.py", line 4
    ...
    ^
SyntaxError: invalid syntax


FileName:stanh.py:
---------------------------

successful


FileName:sequence_scatter.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sequence_scatter.py", line 7, in <module>
    output = fluid.layers.sequence_scatter(input, index, updates)
NameError: name 'index' is not defined


FileName:less_than.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/less_than.py", line 2, in <module>
    less = fluid.layers.less_than(x=label, y=limit)
NameError: name 'label' is not defined


FileName:squeeze.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/squeeze.py", line 7, in <module>
    x = layers.data(name='x', shape=[5, 1, 10])
NameError: name 'layers' is not defined


FileName:RMSPropOptimizer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/RMSPropOptimizer.py", line 8, in <module>
    _, params_grads = optimizer.minimize(cost)
NameError: name 'cost' is not defined


FileName:sequence_expand.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sequence_expand.py", line 10, in <module>
    out = layers.sequence_expand(x=x, y=y, ref_level=0)
NameError: name 'layers' is not defined


FileName:Executor. run_1.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Executor. run_1.py", line 7, in <module>
    cpu = core.CPUPlace()
NameError: name 'core' is not defined


FileName:elementwise_min.py:
---------------------------

  File "./api_codes/elementwise_min.py", line 7
    shape(X) = (2, 3, 4, 5), shape(Y) = (,)
                                         ^
SyntaxError: invalid syntax


FileName:embedding.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/embedding.py", line 7, in <module>
    dict_size = len(dataset.ids)
NameError: name 'dataset' is not defined


FileName:ExecutionStrategy.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/ExecutionStrategy.py", line 11, in <module>
    loss_name=loss.name,
NameError: name 'loss' is not defined


FileName:bilinear_tensor_product.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/bilinear_tensor_product.py", line 7, in <module>
    tensor = bilinear_tensor_product(x=layer1, y=layer2, size=1000)
NameError: name 'bilinear_tensor_product' is not defined


FileName:nce.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/nce.py", line 10, in <module>
    words.append(layers.data(
NameError: name 'layers' is not defined


FileName:elementwise_mul.py:
---------------------------

  File "./api_codes/elementwise_mul.py", line 7
    shape(X) = (2, 3, 4, 5), shape(Y) = (,)
                                         ^
SyntaxError: invalid syntax


FileName:box_coder.py:
---------------------------

successful


FileName:open_files.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/open_files.py", line 11, in <module>
    dtypes=['float32', 'int64'])
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 901, in open_files
    shape_concat.extend(shape)
TypeError: 'int' object is not iterable


FileName:image_resize.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/image_resize.py", line 7, in <module>
    out = fluid.layers.image_resize(input, out_shape=[12, 12], resample="NEAREST")
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 7208, in image_resize
    dtype = helper.input_dtype()
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 95, in input_dtype
    dtype = each.dtype
AttributeError: 'NoneType' object has no attribute 'dtype'


FileName:prelu.py:
---------------------------

successful


FileName:append_LARS.py:
---------------------------

  File "./api_codes/append_LARS.py", line 8
    / (sqrt(sumsq(gradient))+ weight_decay * sqrt(sumsq(param)))
    ^
IndentationError: unexpected indent


FileName:cumsum.py:
---------------------------

successful


FileName:inverse_time_decay_1.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/inverse_time_decay_1.py", line 7, in <module>
    if staircase == True:
NameError: name 'staircase' is not defined


FileName:group_norm.py:
---------------------------

successful


FileName:roi_align.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/roi_align.py", line 7, in <module>
    align_out = fluid.layers.roi_align(input=x,
NameError: name 'x' is not defined


FileName:yolov3_loss.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/yolov3_loss.py", line 14, in <module>
    ignore_thresh=0.7, downsample_ratio=32)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/detection.py", line 628, in yolov3_loss
    attrs=attrs)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1663, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1070, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected dim_gtbox[2] == 4, but received dim_gtbox[2]:5 != 4:4.
Input(GTBox) dim[2] should be 5 at [/home/users/dongdaxiang/github_develop/Paddle/paddle/fluid/operators/detection/yolov3_loss_op.cc:57]
PaddlePaddle Call Stacks: 
0       0x7f456b940a38p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f456b940d87p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f456cf6632dp paddle::operators::Yolov3LossOp::InferShape(paddle::framework::InferShapeContext*) const + 4445
3       0x7f456ba9c48ep paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 862
4       0x7f456b9f1dfcp
5       0x7f456b973804p
6       0x7f46693e1bb8p PyEval_EvalFrameEx + 25016
7       0x7f46693e50bdp PyEval_EvalCodeEx + 2061
8       0x7f466935bf85p
9       0x7f4669329df3p PyObject_Call + 67
10      0x7f46693389cdp
11      0x7f4669329df3p PyObject_Call + 67
12      0x7f4669397bafp
13      0x7f466939446fp
14      0x7f4669329df3p PyObject_Call + 67
15      0x7f46693df4a6p PyEval_EvalFrameEx + 15014
16      0x7f46693e50bdp PyEval_EvalCodeEx + 2061
17      0x7f466935bf85p
18      0x7f4669329df3p PyObject_Call + 67
19      0x7f46693def97p PyEval_EvalFrameEx + 13719
20      0x7f46693e50bdp PyEval_EvalCodeEx + 2061
21      0x7f46693e2345p PyEval_EvalFrameEx + 26949
22      0x7f46693e50bdp PyEval_EvalCodeEx + 2061
23      0x7f46693e2345p PyEval_EvalFrameEx + 26949
24      0x7f46693e50bdp PyEval_EvalCodeEx + 2061
25      0x7f46693e51f2p PyEval_EvalCode + 50
26      0x7f466940df42p PyRun_FileExFlags + 146
27      0x7f466940f2d9p PyRun_SimpleFileExFlags + 217
28      0x7f466942500dp Py_Main + 3149
29      0x7f4668622bd5p __libc_start_main + 245
30            0x4007a1p



FileName:sequence_pool.py:
---------------------------

successful


FileName:clip.py:
---------------------------

successful


FileName:inverse_time_decay.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/inverse_time_decay.py", line 14, in <module>
    sgd_optimizer.minimize(avg_cost)
NameError: name 'avg_cost' is not defined


FileName:target_assign.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/target_assign.py", line 7, in <module>
    matched_indices, matched_dist = fluid.layers.bipartite_match(iou)
NameError: name 'iou' is not defined


FileName:one_hot.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/one_hot.py", line 7, in <module>
    label = layers.data(name="label", shape=[1], dtype="float32")
NameError: name 'layers' is not defined


FileName:prior_box.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/prior_box.py", line 8, in <module>
    input=conv1,
NameError: name 'conv1' is not defined


FileName:random_data_generator.py:
---------------------------

successful


FileName:huber_loss_1.py:
---------------------------

  File "./api_codes/huber_loss_1.py", line 7
    huber\_loss = delta * (label - input) - 0.5 * delta * delta
                                                              ^
SyntaxError: unexpected character after line continuation character


FileName:crf_decoding.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/crf_decoding.py", line 7, in <module>
    crf_decode = layers.crf_decoding(
NameError: name 'layers' is not defined


FileName:pool3d.py:
---------------------------

successful


FileName:elementwise_add.py:
---------------------------

  File "./api_codes/elementwise_add.py", line 7
    shape(X) = (2, 3, 4, 5), shape(Y) = (,)
                                         ^
SyntaxError: invalid syntax


FileName:pad.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/pad.py", line 9, in <module>
    x=x, paddings=[0, 1, 1, 2], pad_value=0.)
NameError: name 'x' is not defined


FileName:pow.py:
---------------------------

successful


FileName:DataFeedDesc. desc.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DataFeedDesc. desc.py", line 7, in <module>
    data_feed = fluid.DataFeedDesc('data.proto')
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/data_feed_desc.py", line 72, in __init__
    with open(proto_file, 'r') as f:
IOError: [Errno 2] No such file or directory: 'data.proto'


FileName:expand.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/expand.py", line 8, in <module>
    out = fluid.layers.expand(x=x, expand_times=[1, 2, 2])
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 8939, in expand
    attrs={'expand_times': expand_times})
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1663, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1070, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected static_cast<size_t>(x_dims.size()) == expand_times.size(), but received static_cast<size_t>(x_dims.size()):2 != expand_times.size():3.
The number of Attr(expand_times)'s value must be equal to the rank of Input(X). at [/home/users/dongdaxiang/github_develop/Paddle/paddle/fluid/operators/expand_op.cc:39]
PaddlePaddle Call Stacks: 
0       0x7f02ff2bfa38p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f02ff2bfd87p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f02ff95bef2p paddle::operators::ExpandOp::InferShape(paddle::framework::InferShapeContext*) const + 2802
3       0x7f02ff41b48ep paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 862
4       0x7f02ff370dfcp
5       0x7f02ff2f2804p
6       0x7f03fe37cbb8p PyEval_EvalFrameEx + 25016
7       0x7f03fe3800bdp PyEval_EvalCodeEx + 2061
8       0x7f03fe2f6f85p
9       0x7f03fe2c4df3p PyObject_Call + 67
10      0x7f03fe2d39cdp
11      0x7f03fe2c4df3p PyObject_Call + 67
12      0x7f03fe332bafp
13      0x7f03fe32f46fp
14      0x7f03fe2c4df3p PyObject_Call + 67
15      0x7f03fe37a4a6p PyEval_EvalFrameEx + 15014
16      0x7f03fe3800bdp PyEval_EvalCodeEx + 2061
17      0x7f03fe2f6f85p
18      0x7f03fe2c4df3p PyObject_Call + 67
19      0x7f03fe379f97p PyEval_EvalFrameEx + 13719
20      0x7f03fe3800bdp PyEval_EvalCodeEx + 2061
21      0x7f03fe37d345p PyEval_EvalFrameEx + 26949
22      0x7f03fe3800bdp PyEval_EvalCodeEx + 2061
23      0x7f03fe37d345p PyEval_EvalFrameEx + 26949
24      0x7f03fe3800bdp PyEval_EvalCodeEx + 2061
25      0x7f03fe3801f2p PyEval_EvalCode + 50
26      0x7f03fe3a8f42p PyRun_FileExFlags + 146
27      0x7f03fe3aa2d9p PyRun_SimpleFileExFlags + 217
28      0x7f03fe3c000dp Py_Main + 3149
29      0x7f03fd5bdbd5p __libc_start_main + 245
30            0x4007a1p



FileName:chunk_eval_2.py:
---------------------------

  File "./api_codes/chunk_eval_2.py", line 7
    Scheme Begin Inside End   Single
               ^
SyntaxError: invalid syntax


FileName:hard_shrink.py:
---------------------------

successful


FileName:conv3d.py:
---------------------------

successful


FileName:relu.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/relu.py", line 7, in <module>
    output = fluid.layers.relu(x)
NameError: name 'x' is not defined


FileName:unsqueeze.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/unsqueeze.py", line 7, in <module>
    x = layers.data(name='x', shape=[5, 10])
NameError: name 'layers' is not defined


FileName:AsyncExecutor. download_data.py:
---------------------------

  File "./api_codes/AsyncExecutor. download_data.py", line 9
    "./data", "afs://
                    ^
SyntaxError: EOL while scanning string literal


FileName:swish.py:
---------------------------

successful


FileName:program_guard_1.py:
---------------------------

  File "./api_codes/program_guard_1.py", line 5
    data = ...
           ^
SyntaxError: invalid syntax


FileName:lod_reset.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/lod_reset.py", line 7, in <module>
    x = layers.data(name='x', shape=[10])
NameError: name 'layers' is not defined


FileName:DataFeedDesc. set_batch_size.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DataFeedDesc. set_batch_size.py", line 7, in <module>
    data_feed = fluid.DataFeedDesc('data.proto')
  File "/home/users/dongdaxiang/paddle_whls/pipe_reader_gpu/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/data_feed_desc.py", line 72, in __init__
    with open(proto_file, 'r') as f:
IOError: [Errno 2] No such file or directory: 'data.proto'


FileName:im2sequence.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/im2sequence.py", line 8, in <module>
    input=layer, stride=[1, 1], filter_size=[2, 2])
NameError: name 'layer' is not defined


FileName:gather.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/gather.py", line 7, in <module>
    output = fluid.layers.gather(x, index)
NameError: name 'x' is not defined


FileName:hard_sigmoid.py:
---------------------------

successful


FileName:GradientClipByNorm.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/GradientClipByNorm.py", line 7, in <module>
    w_param_attrs = flui.ParamAttr(name=None,
NameError: name 'flui' is not defined


FileName:warpctc.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/warpctc.py", line 7, in <module>
    label = fluid.layers.data(shape=[11, 8], dtype='float32', lod_level=1)
TypeError: data() takes at least 2 arguments (3 given)


FileName:ConstantInitializer.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/ConstantInitializer.py", line 7, in <module>
    fc = fluid.layers.fc(input=x, size=10,
NameError: name 'x' is not defined


FileName:lstm.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/lstm.py", line 7, in <module>
    input = embedding
NameError: name 'embedding' is not defined


FileName:logical_or.py:
---------------------------

successful


FileName:layer_norm.py:
---------------------------

successful


FileName:increment.py:
---------------------------

successful


FileName:multiplex.py:
---------------------------

successful


FileName:logical_and.py:
---------------------------

successful


FileName:argsort.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/argsort.py", line 7, in <module>
    input = fluid.layers.data(data=[2, 3])
TypeError: data() got an unexpected keyword argument 'data'


FileName:GradientClipByValue.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/GradientClipByValue.py", line 12, in <module>
    clip=fluid.clip.GradientClipByValue(-1.0, 1.0))
TypeError: __init__() got an unexpected keyword argument 'clip'


FileName:DataFeeder_1(1).py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/DataFeeder_1(1).py", line 8, in <module>
    feeder = fluid.DataFeeder(place=place, feed_list=[data, label])
NameError: name 'data' is not defined


FileName:sequence_enumerate.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/sequence_enumerate.py", line 7, in <module>
    x = fluid.layers.data(shape[30, 1], dtype='int32', lod_level=1)
NameError: name 'shape' is not defined


FileName:noam_decay.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/noam_decay.py", line 8, in <module>
    lr_value = np.power(d_model, -0.5) * np.min([
NameError: name 'd_model' is not defined


FileName:create_parameter.py:
---------------------------

successful


FileName:While.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/While.py", line 7, in <module>
    d0 = layers.data("d0", shape=[10], dtype='float32')
NameError: name 'layers' is not defined


FileName:tensor_array_to_tensor.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/tensor_array_to_tensor.py", line 7, in <module>
    output, output_index = fluid.layers.tensor_array_to_tensor(input=tensor_array)
NameError: name 'tensor_array' is not defined


FileName:slice.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/slice.py", line 11, in <module>
    input = layers.data(
NameError: name 'layers' is not defined


FileName:Executor. run_2.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/Executor. run_2.py", line 7, in <module>
    x = numpy.random.random(size=(10, 1)).astype('float32')
NameError: name 'numpy' is not defined


FileName:exponential_decay_1.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/exponential_decay_1.py", line 7, in <module>
    if staircase == True:
NameError: name 'staircase' is not defined


FileName:load_params.py:
---------------------------

successful


FileName:dice_loss.py:
---------------------------

  File "./api_codes/dice_loss.py", line 8
    loss = fluid.layers.dice_loss(input=predictions, label=label, 2)
SyntaxError: non-keyword arg after keyword arg


FileName:DataFeeder.py:
---------------------------

successful


FileName:chunk_eval_1.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/chunk_eval_1.py", line 7, in <module>
    tag_type = label % num_tag_type
NameError: name 'label' is not defined


FileName:shape.py:
---------------------------

Traceback (most recent call last):
  File "./api_codes/shape.py", line 7, in <module>
    input = layers.data(
NameError: name 'layers' is not defined


FileName:ctc_greedy_decoder.py:
---------------------------

successful


FileName:create_array.py:
---------------------------

successful
