.. _cn_api_distributed_fleet_utils_fs_ExecuteError:

ExecuteError
-------------------------------

.. py:class:: paddle.distributed.fleet.utils.fs.ExecuteError




